# generated by datamodel-codegen:
#   filename:  network-world-state.openapi.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    confloat,
    conint,
    constr,
)


class Unit(Enum):
    s = 's'


class ScenarioTime(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: confloat(ge=0.0) = Field(..., description='自场景起点开始累计的时间值。')
    unit: Unit = Field(..., description='场景时间统一以秒表示。')


class Name(Enum):
    network_world_state = 'network-world-state'


class SchemaMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Name = Field(..., description='Schema 固定名称。')
    version: str = Field(
        ..., description='Schema 版本。第一阶段建议使用语义化或显式版本号，例如 0.1。'
    )


class X(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Y(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Z(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Vx(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Vy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Vz(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Velocity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vx: Vx = Field(..., description='X 轴速度。')
    vy: Vy = Field(..., description='Y 轴速度。')
    vz: Vz = Field(..., description='Z 轴速度。')


class Roll(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Pitch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Yaw(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Orientation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    roll: Roll | None = Field(None, description='横滚角。')
    pitch: Pitch | None = Field(None, description='俯仰角。')
    yaw: Yaw | None = Field(None, description='偏航角。')


class EnvironmentType(Enum):
    SPACE = 'SPACE'
    TERRESTRIAL = 'TERRESTRIAL'
    AIR = 'AIR'
    SEA = 'SEA'
    MIXED = 'MIXED'
    GENERIC = 'GENERIC'


class Temperature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Pressure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class RainRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class CloudAttenuation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Atmosphere(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    temperature: Temperature | None = Field(None, description='环境温度。')
    pressure: Pressure | None = Field(None, description='环境气压。')
    humidity: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='相对湿度，建议使用 0~1。'
    )
    rain_rate: RainRate | None = Field(None, description='降雨率。')
    cloud_attenuation: CloudAttenuation | None = Field(None, description='云衰减。')


class BackgroundNoise(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class InterferenceRegion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interference_id: str = Field(..., description='干扰对象唯一标识。')
    description: str | None = Field(None, description='干扰源的人类可读说明。')
    parameters: dict[str, Any] | None = Field(
        None, description='由数据源提供的干扰参数。Schema 对其保持开放。'
    )


class ElectromagneticEnvironment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    background_noise: BackgroundNoise | None = Field(None, description='背景噪声功率。')
    interference_regions: list[InterferenceRegion] | None = Field(
        None, description='场景中的干扰区域或干扰源集合。'
    )


class CpuComputeCapacity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class MemoryCapacity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class ComputeCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cpu_cores: conint(ge=0) | None = Field(
        None, description='CPU 逻辑/物理核心数，具体口径由数据源约定。'
    )
    cpu_compute_capacity: CpuComputeCapacity | None = Field(
        None, description='CPU 理论计算能力。'
    )
    memory_capacity: MemoryCapacity | None = Field(None, description='内存总容量。')


class TerminalType(Enum):
    LASER = 'LASER'
    RF = 'RF'
    MICROWAVE = 'MICROWAVE'
    ETHERNET = 'ETHERNET'
    OPTICAL = 'OPTICAL'
    RADIO = 'RADIO'
    GENERIC = 'GENERIC'


class Duplex(Enum):
    HALF = 'HALF'
    FULL = 'FULL'
    UNKNOWN = 'UNKNOWN'


class MaxDataRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class MaxRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class FieldOfView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class MaxTrackingRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class AntennaGain(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class MaxTransmitPower(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class CommunicationTerminalCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    terminal_id: str = Field(..., description='通信终端在所属节点内的唯一标识。')
    terminal_type: TerminalType = Field(..., description='通信终端类型。')
    enabled: bool = Field(..., description='该能力对象是否在本场景中启用。')
    duplex: Duplex | None = Field(None, description='双工模式。')
    max_data_rate: MaxDataRate = Field(..., description='终端理论最大数据速率。')
    max_range: MaxRange | None = Field(None, description='终端理论最大通信距离。')
    supported_frequencies: list[float] | None = Field(
        None,
        description='支持的中心频率或离散频点列表；需要频段时可结合 supported_bands。',
    )
    supported_bands: list[str] | None = Field(
        None, description='支持的频段名称或项目内部频段标识。'
    )
    pointing_required: bool | None = Field(
        None, description='是否要求定向指向或跟踪，例如激光终端通常为 true。'
    )
    field_of_view: FieldOfView | None = Field(None, description='终端视场角。')
    max_tracking_rate: MaxTrackingRate | None = Field(
        None, description='最大跟踪角速度。'
    )
    antenna_type: str | None = Field(
        None, description='天线/光学口径等终端辐射/接收结构类型。'
    )
    antenna_gain: AntennaGain | None = Field(None, description='天线增益。')
    max_transmit_power: MaxTransmitPower | None = Field(
        None, description='最大发射功率。'
    )
    extensions: dict[str, Any] | None = Field(
        None, description='终端类型特有的扩展能力参数。'
    )


class StorageCapacity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class NodeCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    compute: ComputeCapability | None = None
    storage_capacity: StorageCapacity | None = Field(
        None, description='节点本地存储总容量。'
    )
    communication_terminals: list[CommunicationTerminalCapability]
    extensions: dict[str, Any] | None = Field(None, description='节点特有能力扩展。')


class TxRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class RxRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class CurrentFrequency(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class CurrentPower(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class NodeType(Enum):
    SATELLITE = 'SATELLITE'
    GROUND_STATION = 'GROUND_STATION'
    AIRCRAFT = 'AIRCRAFT'
    UAV = 'UAV'
    VEHICLE = 'VEHICLE'
    SHIP = 'SHIP'
    SERVER = 'SERVER'
    ROUTER = 'ROUTER'
    SWITCH = 'SWITCH'
    TERMINAL = 'TERMINAL'
    GENERIC = 'GENERIC'


class L2Endpoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: str = Field(..., description='引用 nodes[].node_id。')
    terminal_id: str = Field(..., description='引用对应节点的 communication terminal。')


class LinkClass(Enum):
    ISL = 'ISL'
    SPACE_GROUND = 'SPACE_GROUND'
    TERRESTRIAL = 'TERRESTRIAL'
    AIR_GROUND = 'AIR_GROUND'
    AIR_AIR = 'AIR_AIR'
    SEA_GROUND = 'SEA_GROUND'
    GENERIC = 'GENERIC'


class Medium(Enum):
    RF = 'RF'
    LASER = 'LASER'
    MICROWAVE = 'MICROWAVE'
    ETHERNET = 'ETHERNET'
    FIBER = 'FIBER'
    OPTICAL = 'OPTICAL'
    GENERIC = 'GENERIC'


class Status(Enum):
    UP = 'UP'
    DOWN = 'DOWN'
    DEGRADED = 'DEGRADED'
    UNKNOWN = 'UNKNOWN'


class Capacity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class AvailableBandwidth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class PropagationDelay(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class TransmissionDelay(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Jitter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Family(Enum):
    IPV4 = 'IPV4'
    IPV6 = 'IPV6'


class IPAddress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str = Field(..., description='IPv4 或 IPv6 地址字符串。')
    prefix_length: conint(ge=0, le=128) = Field(..., description='前缀长度。')
    family: Family = Field(..., description='地址族。')
    primary: bool = Field(..., description='是否为该 L3 接口主地址。')


class L3LogicalEndpoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: str
    l3_interface_id: str


class Type(Enum):
    DIRECT = 'DIRECT'
    TUNNEL = 'TUNNEL'
    OVERLAY = 'OVERLAY'
    GENERIC = 'GENERIC'


class Type1(Enum):
    NODE = 'NODE'
    PREFIX = 'PREFIX'
    ADDRESS = 'ADDRESS'


class Destination(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type1 = Field(..., description='目的对象类型。')
    value: str = Field(..., description='node_id、IP prefix 或具体 IP address。')


class Derived(Enum):
    boolean_True = True


class ReachabilityEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_node: str
    destination: Destination
    reachable: bool
    derived: Derived = Field(..., description='标识该记录为派生状态。')


class NextHop(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: str = Field(..., description='下一跳节点。')
    l3_interface_id: str = Field(..., description='出接口。')
    weight: confloat(ge=0.0) = Field(..., description='多路径权重。单路径通常为 1。')


class TotalDelay(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class BottleneckCapacity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class PathMetrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hop_count: conint(ge=0)
    total_delay: TotalDelay = Field(..., description='端到端总时延。')
    packet_loss_rate: confloat(ge=0.0, le=1.0)
    bottleneck_capacity: BottleneckCapacity = Field(..., description='路径瓶颈容量。')


class L3Path(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path_id: str
    source_node: str
    destination_node: str
    nodes: list[str] = Field(..., min_length=1)
    logical_links: list[str]
    valid: bool
    derived: Derived
    metrics: PathMetrics


class L3AggregateState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reachable_pair_ratio: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='可达节点对比例。'
    )
    connected_components: conint(ge=0) | None = Field(
        None, description='当前三层连通分量数量。'
    )
    isolated_nodes: list[str] | None = Field(None, description='当前孤立节点 ID。')


class RequestedRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class TotalDataSize(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Status1(Enum):
    QUEUED = 'QUEUED'
    ACTIVE = 'ACTIVE'
    PAUSED = 'PAUSED'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class OfferedRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class AllocatedRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class ActualThroughput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Rtt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class BytesTotal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class BytesSent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class BytesDelivered(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class BytesRemaining(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class FlowState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status1 = Field(..., description='Flow 生命周期状态。')
    offered_rate: OfferedRate = Field(..., description='数据源实际尝试发送的速率。')
    allocated_rate: AllocatedRate = Field(
        ..., description='网络为该 Flow 分配的速率/带宽。'
    )
    actual_throughput: ActualThroughput = Field(..., description='实际有效吞吐。')
    rtt: Rtt | None = Field(None, description='往返时延。')
    loss_rate: confloat(ge=0.0, le=1.0)
    bytes_total: BytesTotal | None = Field(None, description='Flow 总字节数。')
    bytes_sent: BytesSent = Field(..., description='源端已经发送的字节数。')
    bytes_delivered: BytesDelivered = Field(
        ..., description='目的端已经成功接收的字节数。'
    )
    bytes_remaining: BytesRemaining | None = Field(
        None, description='剩余待发送/待完成字节数。'
    )


class TransportType(Enum):
    TCP = 'TCP'
    UDP = 'UDP'
    RAW = 'RAW'
    GENERIC = 'GENERIC'


class Type2(Enum):
    LINK = 'LINK'
    NODE_COMPUTE = 'NODE_COMPUTE'
    NODE_STORAGE = 'NODE_STORAGE'
    TERMINAL = 'TERMINAL'
    GENERIC = 'GENERIC'


class ResourceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type2 = Field(..., description='被分配的资源类型。')
    resource_id: str = Field(..., description='对应资源对象 ID。')


class Type3(Enum):
    FLOW = 'FLOW'
    TASK = 'TASK'


class ConsumerRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type3 = Field(..., description='资源消费者类型。')
    consumer_id: str


class Bandwidth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Compute(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class TotalOfferedTraffic(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class TotalDeliveredTraffic(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class TrafficAggregateState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    total_offered_traffic: TotalOfferedTraffic = Field(
        ..., description='全网总 offered traffic。'
    )
    total_delivered_traffic: TotalDeliveredTraffic = Field(
        ..., description='全网总 delivered traffic。'
    )
    congested_links: list[str] = Field(..., description='被判定为拥塞的 link_id 列表。')


class Class(Enum):
    BACKGROUND = 'BACKGROUND'
    NORMAL = 'NORMAL'
    HIGH = 'HIGH'
    MISSION_CRITICAL = 'MISSION_CRITICAL'
    EMERGENCY = 'EMERGENCY'


class TaskPriority(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: int = Field(..., description='优先级数值，值越大表示优先级越高。')
    class_: Class = Field(..., alias='class', description='语义优先级。')


class ConstraintType(Enum):
    HARD = 'HARD'
    SOFT = 'SOFT'
    OBJECTIVE = 'OBJECTIVE'


class Constraint(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    enabled: bool
    constraint_type: ConstraintType = Field(
        ..., description='HARD=必须满足，SOFT=尽量满足，OBJECTIVE=优化方向。'
    )


class Max(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Latency(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool
    max: Max | None = Field(None, description='任务允许的最大时延。')
    constraint_type: ConstraintType = Field(..., description='时延要求约束类型。')


class Reliability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool
    minimum_delivery_probability: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='最低成功交付概率。'
    )
    constraint_type: ConstraintType = Field(..., description='可靠性约束类型。')


class Minimum(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Preferred(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class Throughput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool
    minimum: Minimum | None = Field(None, description='最低吞吐要求。')
    preferred: Preferred | None = Field(None, description='偏好的目标吞吐。')


class Completion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    must_complete: bool = Field(..., description='任务是否要求最终完成。')
    deadline_required: bool = Field(..., description='是否要求在 deadline 前完成。')


class TaskRequirements(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    latency: Latency
    reliability: Reliability
    throughput: Throughput
    completion: Completion


class Status2(Enum):
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    PAUSED = 'PAUSED'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'


class SatisfactionState(Enum):
    SatisfactionStateSatisfied = 'SATISFIED'
    SatisfactionStateViolated = 'VIOLATED'
    SatisfactionStateInProgress = 'IN_PROGRESS'
    SatisfactionStateUnknown = 'UNKNOWN'


class RequirementSatisfactionState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    overall_satisfied: SatisfactionState | None = Field(
        None, description='总体要求满足状态。'
    )
    latency_satisfied: SatisfactionState | None = Field(
        None, description='时延 SLA 满足状态。'
    )
    reliability_satisfied: SatisfactionState | None = Field(
        None, description='可靠性/交付率 SLA 满足状态。'
    )
    throughput_satisfied: SatisfactionState | None = Field(
        None, description='吞吐量 SLA 满足状态。'
    )
    deadline_satisfied: SatisfactionState | None = Field(
        None, description='截止时间 SLA 满足状态。'
    )


class PayloadSize(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class DeliveryMode(Enum):
    GUARANTEED = 'GUARANTEED'
    BEST_EFFORT = 'BEST_EFFORT'
    FIRE_AND_FORGET = 'FIRE_AND_FORGET'


class CompletionCriterion(Enum):
    SOURCE_SENT = 'SOURCE_SENT'
    DESTINATION_RECEIVED = 'DESTINATION_RECEIVED'
    DESTINATION_ACKNOWLEDGED = 'DESTINATION_ACKNOWLEDGED'


class Connectivity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool
    preserve_global_connectivity: bool
    minimum_reachable_pair_ratio: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='可选最低全局可达节点对比例。'
    )


class TaskAssurance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool
    priority_aware: bool
    preemption_allowed: bool
    respect_task_qos: bool


class ResourceEfficiency(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool
    avoid_congestion: bool
    load_balance: bool


class ObjectiveWeights(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectivity: confloat(ge=0.0) | None = None
    task_assurance: confloat(ge=0.0) | None = None
    latency: confloat(ge=0.0) | None = None
    reliability: confloat(ge=0.0) | None = None
    resource_efficiency: confloat(ge=0.0) | None = None


class Type4(Enum):
    NODE = 'NODE'
    LINK = 'LINK'
    TERMINAL = 'TERMINAL'
    TASK = 'TASK'
    PHYSICAL_WORLD = 'PHYSICAL_WORLD'
    INTENT = 'INTENT'
    GENERIC = 'GENERIC'


class TargetRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type4 = Field(..., description='事件或外部行为的目标对象类型。')
    id: str | None = Field(
        None, description='目标对象 ID。全局对象可为空，例如 PHYSICAL_WORLD。'
    )


class EventType(Enum):
    NODE_FAILURE = 'NODE_FAILURE'
    LINK_FAILURE = 'LINK_FAILURE'
    ENVIRONMENT_CHANGE = 'ENVIRONMENT_CHANGE'
    INTERFERENCE = 'INTERFERENCE'
    TERMINAL_FAILURE = 'TERMINAL_FAILURE'
    GENERIC = 'GENERIC'


class Duration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class WorldEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: str
    occurred_at: ScenarioTime
    event_type: EventType = Field(..., description='事件类型。')
    target: TargetRef
    parameters: dict[str, Any] | None = Field(
        None, description='事件特有参数，例如故障程度、干扰功率、环境变化量。'
    )
    duration: Duration | None = Field(None, description='事件持续时间。')


class ActionType(Enum):
    TASK_SUBMIT = 'TASK_SUBMIT'
    TASK_CANCEL = 'TASK_CANCEL'
    TASK_MODIFY = 'TASK_MODIFY'
    NODE_FORCE_ENABLE = 'NODE_FORCE_ENABLE'
    NODE_FORCE_DISABLE = 'NODE_FORCE_DISABLE'
    LINK_FORCE_UP = 'LINK_FORCE_UP'
    LINK_FORCE_DOWN = 'LINK_FORCE_DOWN'
    ENVIRONMENT_CHANGE = 'ENVIRONMENT_CHANGE'
    INTENT_CHANGE = 'INTENT_CHANGE'


class ExternalAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_id: str
    executed_at: ScenarioTime
    action_type: ActionType = Field(..., description='外部主动干预类型。')
    target: TargetRef
    parameters: dict[str, Any] | None = Field(
        None,
        description='Action 特有参数。例如 TASK_SUBMIT 可包含 task 定义，INTENT_CHANGE 可包含新的 intent 字段。',
    )


class AverageRtt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float = Field(
        ..., description='数值。为空表示该指标当前未采集、不可用或不适用于当前对象。'
    )
    unit: str = Field(
        ...,
        description='物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。',
    )


class NetworkDerivedMetrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reachable_pair_ratio: confloat(ge=0.0, le=1.0) | None = None
    average_path_length: confloat(ge=0.0) | None = None
    average_rtt: AverageRtt | None = Field(None, description='全网平均 RTT。')
    packet_loss_rate: confloat(ge=0.0, le=1.0) | None = None
    maximum_link_utilization: confloat(ge=0.0) | None = None
    congested_link_count: conint(ge=0) | None = None
    reachability: list[ReachabilityEntry] | None = Field(
        None, description='由转发状态推导得到的端到端可达性集合（派生状态）。'
    )
    paths: list[L3Path] | None = Field(
        None, description='由转发状态推导得到的端到端路径集合（派生状态）。'
    )


class TaskDerivedMetrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    total_tasks: conint(ge=0) | None = None
    running_tasks: conint(ge=0) | None = None
    completed_tasks: conint(ge=0) | None = None
    failed_tasks: conint(ge=0) | None = None
    deadline_violation_count: conint(ge=0) | None = None
    high_priority_satisfaction_ratio: confloat(ge=0.0, le=1.0) | None = None


class DerivedMetrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    network: NetworkDerivedMetrics
    tasks: TaskDerivedMetrics


class Scale(Enum):
    TimeScaleUTC = 'UTC'
    TimeScaleTAI = 'TAI'
    TimeScaleTT = 'TT'
    TimeScaleTDB = 'TDB'


class Instant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: constr(
        pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:([0-5][0-9]|60)(\.[0-9]+)?$'
    ) = Field(
        ...,
        description='不带时区后缀的扩展 ISO-8601 时刻 YYYY-MM-DDThh:mm:ss[.fraction]；秒值 60 只允许用于经版本化 leap-second 数据验证后的 UTC。',
        examples=['2026-01-01T00:00:00'],
    )
    scale: Scale = Field(
        ...,
        description='时间尺度。UTC=协调世界时；TAI=国际原子时；TT=地球时；TDB=太阳系质心力学时。没有 scale 的时刻无法被独立解释。',
    )


class TimeBase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scenario_epoch: Instant = Field(
        ..., description='scenario_time = 0 所对应的绝对时刻。'
    )
    simulation_start: Instant = Field(
        ...,
        description='仿真真正开始推进的绝对时刻。通常与 scenario_epoch 相同；外部系统在正式推进前预置初始状态时二者可以不同。',
    )
    tick_s: PositiveFloat | None = Field(
        None,
        description='逻辑仿真 tick 长度，单位为秒。用于表达观测的最细时间粒度，也是时序对齐 binning 窗口的下界。',
    )


class Sampling(Enum):
    SamplingExact = 'Exact'
    SamplingPrevious = 'Previous'
    SamplingNearest = 'Nearest'


class ObservationStamp(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    observed_at_instant: Instant | None = Field(
        None, description='源系统报告该值产生的绝对时刻。'
    )
    observed_at_scenario_time: ScenarioTime | None = Field(
        None, description='该值对齐到世界模型时间轴后的时刻。'
    )
    valid_from: ScenarioTime | None = Field(
        None, description='该值开始适用的场景时刻。'
    )
    valid_until: ScenarioTime | None = Field(
        None, description='该值不再适用的场景时刻（不含）；省略表示一直有效。'
    )
    source_system: constr(min_length=1) = Field(
        ..., description='产生该观测的外部系统名称。'
    )
    source_record_id: str | None = Field(
        None, description='源系统内部的记录标识，不要求全局唯一。'
    )
    sampling: Sampling | None = Field(
        None,
        description='该观测相对请求时刻的采样策略。Replay 场景必须显式声明，不允许由 adapter 自行选择，否则回放结果不可复现。',
    )


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_system: constr(min_length=1) = Field(
        ..., description='产生原始数据的外部系统名称。'
    )
    source_record_ids: list[str] | None = Field(
        None, description='参与该快照的原始记录标识。'
    )
    adapter: str | None = Field(None, description='执行映射的 adapter 名称。')
    adapter_version: str | None = Field(
        None, description='映射规范（mapping spec）的名称与版本；用于精确复现数据集。'
    )
    simulation_run_id: str | None = Field(None, description='外部仿真系统的运行标识。')
    raw_source_refs: list[str] | None = Field(
        None, description='原始文件或流的引用（路径、URI 或对象名）。'
    )
    imported_at: AwareDatetime | None = Field(
        None, description='导入发生的墙上时钟时间；仅用于审计，不参与任何计算。'
    )
    notes: str | None = None


class State(Enum):
    AvailabilityObserved = 'observed'
    AvailabilityDerived = 'derived'
    AvailabilityUnavailable = 'unavailable'
    AvailabilityUnknown = 'unknown'


class Availability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    state: State = Field(
        ...,
        description='observed=直接观测到；derived=由其他观测计算得到；unavailable=当前条件下不可观测；unknown=来源未声明。',
    )
    coverage_ratio: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='该量在聚合范围内的覆盖率；1 表示完整覆盖。'
    )
    partial: bool | None = Field(
        None,
        description='true 表示结果基于部分可见数据得出，只能解释为部分统计，不能当作完整结论。',
    )
    reason: str | None = Field(
        None,
        description='unavailable / unknown / partial 的原因标识，便于消费方区分「源不支持该量」与「暂时不可达」。',
    )


class Vec3(RootModel[list[float]]):
    root: list[float] = Field(
        ...,
        description='三维向量 [x, y, z]，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Vec3，语义保持一致。 单位由引用它的字段名声明显式声明（例如 _m、_m_s、_rad_s），不得依赖调用方推测。',
        max_length=3,
        min_length=3,
    )


class QuaternionXYZW(RootModel[list[float]]):
    root: list[float] = Field(
        ...,
        description='单位四元数 [x, y, z, w]（标量在最后），vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 QuaternionXYZW，语义保持一致。 表示从字段名所指 source frame 到 target frame 的主动旋转；分量顺序固定为 XYZW，禁止使用 wxyz 顺序。',
        max_length=4,
        min_length=4,
    )


class Type5(Enum):
    FrameKindNamedFrame = 'NamedFrame'


class NamedFrameRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['NamedFrame'] = Field(..., description='引用种类判别字段。')
    name: constr(min_length=1) = Field(
        ...,
        description='场景内稳定的命名参考系标识；同一场景内唯一，且不得使用显示名。',
    )


class Type6(Enum):
    FrameKindNodeBodyFrame = 'NodeBodyFrame'


class NodeBodyFrameRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['NodeBodyFrame'] = Field(..., description='引用种类判别字段。')
    node: constr(min_length=1) = Field(..., description='场景实体的稳定名称。')


class FrameRef(RootModel[NamedFrameRef | NodeBodyFrameRef]):
    root: NamedFrameRef | NodeBodyFrameRef = Field(
        ...,
        description='参考系引用：命名参考系或场景实体机体系，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 FrameRef，语义保持一致。 任何坐标都必须能通过 FrameRef 独立解释；不得从字段名、实体名或调用方类型猜测参考系。',
        discriminator='type',
    )


class Type7(Enum):
    FrameTransformIdentity = 'Identity'


class IdentityFrameTransform(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['Identity']


class Type8(Enum):
    FrameTransformFixed = 'Fixed'


class FixedFrameTransform(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['Fixed']
    translation_parent_m: Vec3 = Field(
        ..., description='子参考系原点在父参考系中的位置，单位为米。'
    )
    rotation_child_to_parent_xyzw: QuaternionXYZW = Field(
        ..., description='子参考系到父参考系的主动旋转。'
    )


class Type9(Enum):
    FrameTransformUniformRotation = 'UniformRotation'


class UniformRotationFrameTransform(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['UniformRotation']
    epoch: Instant = Field(..., description='相位锚定的历元。')
    origin_parent_m: Vec3 = Field(
        ..., description='子参考系原点在父参考系中的位置，单位为米。'
    )
    axis_parent: Vec3 = Field(
        ..., description='父参考系中的旋转轴；必须为有限非零向量。'
    )
    rate_rad_s: float = Field(..., description='角速度，单位为 rad/s。')
    phase_at_epoch_rad: float = Field(
        ..., description='历元时绕旋转轴的相位，单位为 rad。'
    )


class Type10(Enum):
    FrameTransformEphemeris = 'Ephemeris'


class EphemerisFrameTransform(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['Ephemeris']
    provider: constr(min_length=1) = Field(
        ..., description='版本化空间 provider 的名称。'
    )
    observer: str = Field(..., description='观察者标识。')
    target: str = Field(..., description='目标标识。')
    orientation: str | None = Field(None, description='姿态表达约定。')
    derivative_order: str = Field(..., description='导数阶数约定。')


class FrameTransform(
    RootModel[
        IdentityFrameTransform
        | FixedFrameTransform
        | UniformRotationFrameTransform
        | EphemerisFrameTransform
    ]
):
    root: (
        IdentityFrameTransform
        | FixedFrameTransform
        | UniformRotationFrameTransform
        | EphemerisFrameTransform
    ) = Field(
        ...,
        description='参考系变换链上的一环，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 FrameTransform，语义保持一致。',
        discriminator='type',
    )


class ReferenceFrame(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1) = Field(
        ...,
        description='场景内稳定的命名参考系标识；同一场景内唯一，且不得使用显示名。',
    )
    parent: NamedFrameRef | None = Field(
        None, description='父参考系；省略表示这是根参考系。'
    )
    transform: FrameTransform


class Type11(Enum):
    BodyShapeSphere = 'Sphere'


class SphereBodyShape(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['Sphere']
    radius_m: PositiveFloat = Field(..., description='球半径，单位为米。')


class Type12(Enum):
    BodyShapeOblateEllipsoid = 'OblateEllipsoid'


class OblateEllipsoidBodyShape(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['OblateEllipsoid']
    semi_major_axis_m: PositiveFloat = Field(..., description='长半轴，单位为米。')
    inverse_flattening: PositiveFloat = Field(..., description='扁率倒数 1/f。')


class BodyShape(RootModel[SphereBodyShape | OblateEllipsoidBodyShape]):
    root: SphereBodyShape | OblateEllipsoidBodyShape = Field(
        ...,
        description='天体形状。它同时是大地坐标的 datum：没有 shape 就无法解释经纬高。',
        discriminator='type',
    )


class EnvironmentBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1) = Field(
        ..., description='场景内稳定的环境天体标识；同一场景内唯一。'
    )
    shape: BodyShape
    inertial_frame: FrameRef = Field(..., description='该天体的惯性参考系。')
    fixed_frame: FrameRef = Field(
        ..., description='该天体的固连参考系；大地坐标只允许与该帧组合。'
    )


class Type13(Enum):
    PositionFormatCartesian = 'Cartesian'


class CartesianObservationFormat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['Cartesian']


class Type14(Enum):
    PositionFormatGeodetic = 'Geodetic'


class GeodeticObservationFormat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['Geodetic']
    body: constr(min_length=1) = Field(
        ..., description='场景内稳定的环境天体标识；同一场景内唯一。'
    )


class ObservationPositionFormat(
    RootModel[CartesianObservationFormat | GeodeticObservationFormat]
):
    root: CartesianObservationFormat | GeodeticObservationFormat = Field(
        ...,
        description='位置表达格式，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 ObservationPositionFormat，语义保持一致。 消费方必须按 response 中解析后的格式解释数值，不得把任意笛卡尔坐标自动当作地球固连坐标。',
        discriminator='type',
    )


class Position(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    frame: FrameRef
    x: X = Field(
        ..., description='X 轴坐标。', examples=[{'value': 6371000, 'unit': 'm'}]
    )
    y: Y = Field(..., description='Y 轴坐标。')
    z: Z = Field(..., description='Z 轴坐标。')


class SpatialEnvironment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default_reference_frame: FrameRef
    earth_model: str | None = Field(
        None, description='地球模型或参考椭球，例如 WGS84。'
    )
    terrain_model_id: str | None = Field(None, description='外部地形模型标识。')
    obstacle_model_id: str | None = Field(None, description='外部障碍物模型标识。')


class PhysicalWorld(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    environment_type: EnvironmentType = Field(
        ...,
        description='场景的宏观物理环境分类，仅用于描述和筛选，不决定核心计算逻辑。',
    )
    spatial_environment: SpatialEnvironment = Field(
        ..., description='空间/地理参考环境。'
    )
    atmosphere: Atmosphere | None = Field(
        None, description='大气环境条件。可由仿真系统直接采集并映射。'
    )
    electromagnetic_environment: ElectromagneticEnvironment | None = Field(
        None, description='电磁背景、噪声和干扰环境。'
    )
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )
    extensions: dict[str, Any] | None = Field(
        None, description='物理世界的扩展属性。扩展字段不应改变核心 Schema 语义。'
    )


class CommunicationTerminalState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    terminal_id: str = Field(
        ...,
        description='引用所属节点 capabilities.communication_terminals 中的 terminal_id。',
    )
    operational: bool = Field(..., description='终端是否处于可工作状态。')
    active: bool = Field(..., description='终端当前是否处于激活/工作状态。')
    tx_rate: TxRate = Field(..., description='当前发送速率。')
    rx_rate: RxRate = Field(..., description='当前接收速率。')
    pointing_direction: dict[str, Any] | None = Field(
        None, description='当前指向信息；具体坐标表达由数据源决定。'
    )
    angular_velocity_body_rad_s: Vec3 | None = Field(
        None,
        description='通信终端/天线云台相对节点机体系的角速度 [wx, wy, wz] (rad/s)。',
    )
    current_frequency: CurrentFrequency | None = Field(
        None, description='当前工作频率。'
    )
    current_power: CurrentPower | None = Field(None, description='当前发射功率。')


class NodeState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    position: Position
    velocity: Velocity
    orientation: Orientation | None = None
    angular_velocity_body_rad_s: Vec3 | None = Field(
        None,
        description='节点绕机体系三轴的角速度 [wx, wy, wz] (rad/s)。姿态演化预测必需。',
    )
    operational: bool = Field(..., description='节点整体是否处于工作状态。')
    faults: list[str] | None = Field(None, description='当前生效的故障/异常标识。')
    cpu_utilization: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='CPU 利用率，统一使用 0~1。'
    )
    memory_utilization: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='内存利用率，统一使用 0~1。'
    )
    communication_terminals: list[CommunicationTerminalState]
    availability: Availability | None = Field(
        None,
        description='该对象动态状态的可观测性。不可观测时不得用默认值填充具体字段，必须在 availability 中显式声明 state=unavailable。',
    )
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )
    extensions: dict[str, Any] | None = Field(None, description='节点动态状态扩展。')


class Node(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: str = Field(..., description='在 world_id 范围内全局唯一的节点 ID。')
    node_type: NodeType = Field(
        ..., description='节点类型。该枚举用于分类，不应驱动核心模型中的场景特化逻辑。'
    )
    name: str | None = Field(None, description='可读名称。')
    enabled: bool = Field(..., description='节点是否属于当前场景。')
    capabilities: NodeCapabilities
    state: NodeState
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )
    extensions: dict[str, Any] | None = Field(None, description='节点级扩展字段。')


class L2Link(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    link_id: str = Field(..., description='L2 Link 全局唯一标识。')
    enabled: bool = Field(..., description='该 Link 是否属于当前场景配置。')
    endpoint_a: L2Endpoint
    endpoint_b: L2Endpoint
    link_class: LinkClass = Field(..., description='场景语义上的链路分类。')
    medium: Medium = Field(..., description='实际通信媒介。')
    status: Status = Field(..., description='链路当前运行状态。')
    capacity: Capacity = Field(..., description='当前有效容量。')
    throughput_bps: confloat(ge=0.0) | None = Field(
        None,
        description='链路当前实际传输吞吐量 (bit/s)。与 capacity 配合用于计算利用率与评估拥塞。',
    )
    available_bandwidth: AvailableBandwidth = Field(..., description='当前可用带宽。')
    utilization: confloat(ge=0.0) = Field(
        ...,
        description='当前利用率。通常建议 0~1；允许数据源保留>1以表达过载时需在导入规范中明确。',
    )
    propagation_delay: PropagationDelay = Field(..., description='传播时延。')
    transmission_delay: TransmissionDelay | None = Field(
        None, description='发送/序列化时延。'
    )
    jitter: Jitter = Field(..., description='时延抖动。')
    packet_loss_rate: confloat(ge=0.0, le=1.0) = Field(
        ..., description='包丢失率，0~1。'
    )
    bit_error_rate: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='可选比特误码率，0~1。'
    )
    availability: Availability | None = Field(
        None,
        description='该对象动态状态的可观测性。不可观测时不得用默认值填充具体字段，必须在 availability 中显式声明 state=unavailable。',
    )
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )
    extensions: dict[str, Any] | None = Field(None, description='链路扩展字段。')


class L2Network(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    links: list[L2Link]


class L3Interface(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    l3_interface_id: str = Field(..., description='L3 接口全局唯一 ID。')
    node_id: str = Field(..., description='所属节点 ID。')
    terminal_id: str | None = Field(None, description='可选关联的 L2/通信终端 ID。')
    enabled: bool = Field(..., description='接口是否启用。')
    addresses: list[IPAddress]
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )


class L3LogicalLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    logical_link_id: str = Field(..., description='三层逻辑链路唯一 ID。')
    endpoint_a: L3LogicalEndpoint
    endpoint_b: L3LogicalEndpoint
    operational: bool = Field(..., description='逻辑链路当前是否有效。')
    type: Type = Field(..., description='三层逻辑连接类型。')
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )


class ForwardingEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    forwarding_id: str = Field(..., description='Forwarding Entry 唯一 ID。')
    node_id: str = Field(..., description='执行该转发决策的节点。')
    destination: Destination
    next_hops: list[NextHop] = Field(..., description='有效下一跳集合。', min_length=1)
    valid_from: ScenarioTime
    valid_until: ScenarioTime | None = Field(
        None, description='可选失效时间。为空表示在当前快照中仍有效。'
    )
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )


class L3Network(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interfaces: list[L3Interface]
    logical_links: list[L3LogicalLink]
    forwarding_entries: list[ForwardingEntry]
    aggregate_state: L3AggregateState | None = None
    extensions: dict[str, Any] | None = None


class TrafficDemand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    demand_id: str
    source_node: str
    destination_node: str
    task_id: str | None = Field(None, description='产生该需求的 Task，可为空。')
    requested_rate: RequestedRate | None = Field(None, description='期望速率。')
    total_data_size: TotalDataSize | None = Field(None, description='待传输数据总量。')
    generated_at: ScenarioTime
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )


class Flow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flow_id: str
    demand_id: str | None = None
    task_id: str | None = None
    source_node: str
    destination_node: str
    transport_type: TransportType = Field(
        ..., description='传输类型；仅作为 Flow 特征，不绑定模型结构。'
    )
    path_id: str | None = Field(None, description='可选引用当前派生 Path。')
    state: FlowState
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )


class ResourceAllocation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allocation_id: str
    resource: ResourceRef
    consumer: ConsumerRef
    bandwidth: Bandwidth | None = Field(None, description='为消费者分配的带宽。')
    compute: Compute | None = Field(None, description='为消费者分配的计算资源。')
    priority: int | None = Field(None, description='该资源分配记录对应的调度优先级。')
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )


class TrafficResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    demands: list[TrafficDemand]
    flows: list[Flow]
    allocations: list[ResourceAllocation]
    aggregate_state: TrafficAggregateState | None = None


class TaskState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status2 = Field(..., description='任务生命周期状态。')
    started_at: ScenarioTime | None = None
    completed_at: ScenarioTime | None = None
    progress: confloat(ge=0.0, le=1.0) = Field(..., description='任务完成进度 0~1。')
    bytes_total: BytesTotal = Field(..., description='任务总数据量。')
    bytes_sent: BytesSent = Field(..., description='源端已发送数据量。')
    bytes_delivered: BytesDelivered = Field(..., description='目的端已成功交付数据量。')
    estimated_completion_time: ScenarioTime | None = Field(
        None, description='预计任务完成的场景绝对时间，而不是剩余时长。'
    )
    requirement_satisfaction: RequirementSatisfactionState | None = Field(
        None,
        description='当前任务关键要求是否被满足。使用三态枚举避免在途任务被误标为未满足（ADR D-0015）。',
    )


class Task(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str
    task_type: str = Field(..., description='任务类型，由业务系统定义。')
    source_node: str
    destinations: list[str] = Field(..., min_length=1)
    payload_size: PayloadSize = Field(..., description='任务总负载/数据规模。')
    submitted_at: ScenarioTime
    earliest_start: ScenarioTime | None = None
    deadline: ScenarioTime | None = None
    priority: TaskPriority
    requirements: TaskRequirements
    delivery_mode: DeliveryMode = Field(
        ...,
        description='GUARANTEED=强调成功交付，BEST_EFFORT=尽力而为，FIRE_AND_FORGET=源端发出即可。',
    )
    completion_criterion: CompletionCriterion = Field(
        ..., description='任务完成的判定语义。'
    )
    can_preempt_others: bool = Field(
        ..., description='该任务是否允许抢占其他任务资源。'
    )
    preemptible: bool = Field(..., description='该任务自身是否允许被其他任务抢占。')
    state: TaskState
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )
    extensions: dict[str, Any] | None = None


class NetworkIntent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectivity: Connectivity
    task_assurance: TaskAssurance
    resource_efficiency: ResourceEfficiency
    objective_weights: ObjectiveWeights | None = Field(
        None, description='可选高层目标权重，可用于条件化世界模型或后续控制研究。'
    )
    stamp: ObservationStamp | None = Field(
        None,
        description='该对象本次观测的溯源与有效窗口。省略表示该对象没有携带观测元数据，此时必须按 Availability 语义处理，而不是假定它一定是最新值。',
    )
    extensions: dict[str, Any] | None = None


class NetworkState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nodes: list[Node]
    l2_network: L2Network
    l3_network: L3Network
    traffic_resource: TrafficResource
    tasks: list[Task]
    network_intent: NetworkIntent
    events: list[WorldEvent] = Field(
        ..., description='与当前快照相关、在该时间窗口内发生的 Event。'
    )
    external_actions: list[ExternalAction] = Field(
        ..., description='与当前快照相关、在该时间窗口内发生的外部主动 Action。'
    )
    derived_metrics: DerivedMetrics | None = Field(None, description='可选派生指标。')


class WorldState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    physical_world: PhysicalWorld | None = Field(
        None, description='外部物理世界与空间几何环境（低频稀疏注入）。'
    )
    network: NetworkState = Field(
        ..., description='内生通信网络完整拓扑、资源与业务状态。'
    )


class NetworkWorldState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: SchemaMetadata = Field(..., alias='schema')
    world_id: str = Field(..., description='场景/世界唯一标识。')
    snapshot_id: str = Field(..., description='当前 World Snapshot 唯一标识。')
    scenario_time: ScenarioTime
    time_base: TimeBase | None = Field(
        None,
        description='把 scenario_time 锚定到绝对时刻的时间基。缺少它时，ObservationStamp 中的 Instant 与 scenario_time 无法互相换算。',
    )
    state: WorldState = Field(
        ..., description='该快照对应的世界状态本体（包含物理环境与网络状态）。'
    )
    availability: Availability | None = Field(
        None,
        description='该快照整体的可观测性/覆盖率。partial=true 的快照只能解释为部分状态，不能当作完整网络结论。',
    )
    provenance: Provenance | None = Field(
        None, description='该快照的数据来源与血缘。离线数据必须携带。'
    )
    extensions: dict[str, Any] | None = Field(None, description='顶层扩展字段。')
