// Package worldstate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package worldstate

import (
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AvailabilityState.
const (
	AvailabilityDerived     AvailabilityState = "derived"
	AvailabilityObserved    AvailabilityState = "observed"
	AvailabilityUnavailable AvailabilityState = "unavailable"
	AvailabilityUnknown     AvailabilityState = "unknown"
)

// Valid indicates whether the value is a known member of the AvailabilityState enum.
func (e AvailabilityState) Valid() bool {
	switch e {
	case AvailabilityDerived:
		return true
	case AvailabilityObserved:
		return true
	case AvailabilityUnavailable:
		return true
	case AvailabilityUnknown:
		return true
	default:
		return false
	}
}

// Defines values for CartesianObservationFormatType.
const (
	PositionFormatCartesian CartesianObservationFormatType = "Cartesian"
)

// Valid indicates whether the value is a known member of the CartesianObservationFormatType enum.
func (e CartesianObservationFormatType) Valid() bool {
	switch e {
	case PositionFormatCartesian:
		return true
	default:
		return false
	}
}

// Defines values for CommunicationTerminalCapabilityDuplex.
const (
	CommunicationTerminalCapabilityDuplexFULL    CommunicationTerminalCapabilityDuplex = "FULL"
	CommunicationTerminalCapabilityDuplexHALF    CommunicationTerminalCapabilityDuplex = "HALF"
	CommunicationTerminalCapabilityDuplexUNKNOWN CommunicationTerminalCapabilityDuplex = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the CommunicationTerminalCapabilityDuplex enum.
func (e CommunicationTerminalCapabilityDuplex) Valid() bool {
	switch e {
	case CommunicationTerminalCapabilityDuplexFULL:
		return true
	case CommunicationTerminalCapabilityDuplexHALF:
		return true
	case CommunicationTerminalCapabilityDuplexUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for CommunicationTerminalCapabilityTerminalType.
const (
	CommunicationTerminalCapabilityTerminalTypeETHERNET  CommunicationTerminalCapabilityTerminalType = "ETHERNET"
	CommunicationTerminalCapabilityTerminalTypeGENERIC   CommunicationTerminalCapabilityTerminalType = "GENERIC"
	CommunicationTerminalCapabilityTerminalTypeLASER     CommunicationTerminalCapabilityTerminalType = "LASER"
	CommunicationTerminalCapabilityTerminalTypeMICROWAVE CommunicationTerminalCapabilityTerminalType = "MICROWAVE"
	CommunicationTerminalCapabilityTerminalTypeOPTICAL   CommunicationTerminalCapabilityTerminalType = "OPTICAL"
	CommunicationTerminalCapabilityTerminalTypeRADIO     CommunicationTerminalCapabilityTerminalType = "RADIO"
	CommunicationTerminalCapabilityTerminalTypeRF        CommunicationTerminalCapabilityTerminalType = "RF"
)

// Valid indicates whether the value is a known member of the CommunicationTerminalCapabilityTerminalType enum.
func (e CommunicationTerminalCapabilityTerminalType) Valid() bool {
	switch e {
	case CommunicationTerminalCapabilityTerminalTypeETHERNET:
		return true
	case CommunicationTerminalCapabilityTerminalTypeGENERIC:
		return true
	case CommunicationTerminalCapabilityTerminalTypeLASER:
		return true
	case CommunicationTerminalCapabilityTerminalTypeMICROWAVE:
		return true
	case CommunicationTerminalCapabilityTerminalTypeOPTICAL:
		return true
	case CommunicationTerminalCapabilityTerminalTypeRADIO:
		return true
	case CommunicationTerminalCapabilityTerminalTypeRF:
		return true
	default:
		return false
	}
}

// Defines values for ConstraintConstraintType.
const (
	ConstraintConstraintTypeHARD      ConstraintConstraintType = "HARD"
	ConstraintConstraintTypeOBJECTIVE ConstraintConstraintType = "OBJECTIVE"
	ConstraintConstraintTypeSOFT      ConstraintConstraintType = "SOFT"
)

// Valid indicates whether the value is a known member of the ConstraintConstraintType enum.
func (e ConstraintConstraintType) Valid() bool {
	switch e {
	case ConstraintConstraintTypeHARD:
		return true
	case ConstraintConstraintTypeOBJECTIVE:
		return true
	case ConstraintConstraintTypeSOFT:
		return true
	default:
		return false
	}
}

// Defines values for ConsumerRefType.
const (
	ConsumerRefTypeFLOW ConsumerRefType = "FLOW"
	ConsumerRefTypeTASK ConsumerRefType = "TASK"
)

// Valid indicates whether the value is a known member of the ConsumerRefType enum.
func (e ConsumerRefType) Valid() bool {
	switch e {
	case ConsumerRefTypeFLOW:
		return true
	case ConsumerRefTypeTASK:
		return true
	default:
		return false
	}
}

// Defines values for DestinationType.
const (
	ADDRESS DestinationType = "ADDRESS"
	NODE    DestinationType = "NODE"
	PREFIX  DestinationType = "PREFIX"
)

// Valid indicates whether the value is a known member of the DestinationType enum.
func (e DestinationType) Valid() bool {
	switch e {
	case ADDRESS:
		return true
	case NODE:
		return true
	case PREFIX:
		return true
	default:
		return false
	}
}

// Defines values for EphemerisFrameTransformType.
const (
	FrameTransformEphemeris EphemerisFrameTransformType = "Ephemeris"
)

// Valid indicates whether the value is a known member of the EphemerisFrameTransformType enum.
func (e EphemerisFrameTransformType) Valid() bool {
	switch e {
	case FrameTransformEphemeris:
		return true
	default:
		return false
	}
}

// Defines values for ExternalActionActionType.
const (
	ExternalActionActionTypeENVIRONMENTCHANGE ExternalActionActionType = "ENVIRONMENT_CHANGE"
	ExternalActionActionTypeINTENTCHANGE      ExternalActionActionType = "INTENT_CHANGE"
	ExternalActionActionTypeLINKFORCEDOWN     ExternalActionActionType = "LINK_FORCE_DOWN"
	ExternalActionActionTypeLINKFORCEUP       ExternalActionActionType = "LINK_FORCE_UP"
	ExternalActionActionTypeNODEFORCEDISABLE  ExternalActionActionType = "NODE_FORCE_DISABLE"
	ExternalActionActionTypeNODEFORCEENABLE   ExternalActionActionType = "NODE_FORCE_ENABLE"
	ExternalActionActionTypeTASKCANCEL        ExternalActionActionType = "TASK_CANCEL"
	ExternalActionActionTypeTASKMODIFY        ExternalActionActionType = "TASK_MODIFY"
	ExternalActionActionTypeTASKSUBMIT        ExternalActionActionType = "TASK_SUBMIT"
)

// Valid indicates whether the value is a known member of the ExternalActionActionType enum.
func (e ExternalActionActionType) Valid() bool {
	switch e {
	case ExternalActionActionTypeENVIRONMENTCHANGE:
		return true
	case ExternalActionActionTypeINTENTCHANGE:
		return true
	case ExternalActionActionTypeLINKFORCEDOWN:
		return true
	case ExternalActionActionTypeLINKFORCEUP:
		return true
	case ExternalActionActionTypeNODEFORCEDISABLE:
		return true
	case ExternalActionActionTypeNODEFORCEENABLE:
		return true
	case ExternalActionActionTypeTASKCANCEL:
		return true
	case ExternalActionActionTypeTASKMODIFY:
		return true
	case ExternalActionActionTypeTASKSUBMIT:
		return true
	default:
		return false
	}
}

// Defines values for FixedFrameTransformType.
const (
	FrameTransformFixed FixedFrameTransformType = "Fixed"
)

// Valid indicates whether the value is a known member of the FixedFrameTransformType enum.
func (e FixedFrameTransformType) Valid() bool {
	switch e {
	case FrameTransformFixed:
		return true
	default:
		return false
	}
}

// Defines values for FlowTransportType.
const (
	FlowTransportTypeGENERIC FlowTransportType = "GENERIC"
	FlowTransportTypeRAW     FlowTransportType = "RAW"
	FlowTransportTypeTCP     FlowTransportType = "TCP"
	FlowTransportTypeUDP     FlowTransportType = "UDP"
)

// Valid indicates whether the value is a known member of the FlowTransportType enum.
func (e FlowTransportType) Valid() bool {
	switch e {
	case FlowTransportTypeGENERIC:
		return true
	case FlowTransportTypeRAW:
		return true
	case FlowTransportTypeTCP:
		return true
	case FlowTransportTypeUDP:
		return true
	default:
		return false
	}
}

// Defines values for FlowStateStatus.
const (
	FlowStateStatusACTIVE    FlowStateStatus = "ACTIVE"
	FlowStateStatusCOMPLETED FlowStateStatus = "COMPLETED"
	FlowStateStatusFAILED    FlowStateStatus = "FAILED"
	FlowStateStatusPAUSED    FlowStateStatus = "PAUSED"
	FlowStateStatusQUEUED    FlowStateStatus = "QUEUED"
)

// Valid indicates whether the value is a known member of the FlowStateStatus enum.
func (e FlowStateStatus) Valid() bool {
	switch e {
	case FlowStateStatusACTIVE:
		return true
	case FlowStateStatusCOMPLETED:
		return true
	case FlowStateStatusFAILED:
		return true
	case FlowStateStatusPAUSED:
		return true
	case FlowStateStatusQUEUED:
		return true
	default:
		return false
	}
}

// Defines values for GeodeticObservationFormatType.
const (
	PositionFormatGeodetic GeodeticObservationFormatType = "Geodetic"
)

// Valid indicates whether the value is a known member of the GeodeticObservationFormatType enum.
func (e GeodeticObservationFormatType) Valid() bool {
	switch e {
	case PositionFormatGeodetic:
		return true
	default:
		return false
	}
}

// Defines values for IPAddressFamily.
const (
	IPV4 IPAddressFamily = "IPV4"
	IPV6 IPAddressFamily = "IPV6"
)

// Valid indicates whether the value is a known member of the IPAddressFamily enum.
func (e IPAddressFamily) Valid() bool {
	switch e {
	case IPV4:
		return true
	case IPV6:
		return true
	default:
		return false
	}
}

// Defines values for IdentityFrameTransformType.
const (
	FrameTransformIdentity IdentityFrameTransformType = "Identity"
)

// Valid indicates whether the value is a known member of the IdentityFrameTransformType enum.
func (e IdentityFrameTransformType) Valid() bool {
	switch e {
	case FrameTransformIdentity:
		return true
	default:
		return false
	}
}

// Defines values for InstantScale.
const (
	TimeScaleTAI InstantScale = "TAI"
	TimeScaleTDB InstantScale = "TDB"
	TimeScaleTT  InstantScale = "TT"
	TimeScaleUTC InstantScale = "UTC"
)

// Valid indicates whether the value is a known member of the InstantScale enum.
func (e InstantScale) Valid() bool {
	switch e {
	case TimeScaleTAI:
		return true
	case TimeScaleTDB:
		return true
	case TimeScaleTT:
		return true
	case TimeScaleUTC:
		return true
	default:
		return false
	}
}

// Defines values for L2LinkLinkClass.
const (
	L2LinkLinkClassAIRAIR      L2LinkLinkClass = "AIR_AIR"
	L2LinkLinkClassAIRGROUND   L2LinkLinkClass = "AIR_GROUND"
	L2LinkLinkClassGENERIC     L2LinkLinkClass = "GENERIC"
	L2LinkLinkClassISL         L2LinkLinkClass = "ISL"
	L2LinkLinkClassSEAGROUND   L2LinkLinkClass = "SEA_GROUND"
	L2LinkLinkClassSPACEGROUND L2LinkLinkClass = "SPACE_GROUND"
	L2LinkLinkClassTERRESTRIAL L2LinkLinkClass = "TERRESTRIAL"
)

// Valid indicates whether the value is a known member of the L2LinkLinkClass enum.
func (e L2LinkLinkClass) Valid() bool {
	switch e {
	case L2LinkLinkClassAIRAIR:
		return true
	case L2LinkLinkClassAIRGROUND:
		return true
	case L2LinkLinkClassGENERIC:
		return true
	case L2LinkLinkClassISL:
		return true
	case L2LinkLinkClassSEAGROUND:
		return true
	case L2LinkLinkClassSPACEGROUND:
		return true
	case L2LinkLinkClassTERRESTRIAL:
		return true
	default:
		return false
	}
}

// Defines values for L2LinkMedium.
const (
	L2LinkMediumETHERNET  L2LinkMedium = "ETHERNET"
	L2LinkMediumFIBER     L2LinkMedium = "FIBER"
	L2LinkMediumGENERIC   L2LinkMedium = "GENERIC"
	L2LinkMediumLASER     L2LinkMedium = "LASER"
	L2LinkMediumMICROWAVE L2LinkMedium = "MICROWAVE"
	L2LinkMediumOPTICAL   L2LinkMedium = "OPTICAL"
	L2LinkMediumRF        L2LinkMedium = "RF"
)

// Valid indicates whether the value is a known member of the L2LinkMedium enum.
func (e L2LinkMedium) Valid() bool {
	switch e {
	case L2LinkMediumETHERNET:
		return true
	case L2LinkMediumFIBER:
		return true
	case L2LinkMediumGENERIC:
		return true
	case L2LinkMediumLASER:
		return true
	case L2LinkMediumMICROWAVE:
		return true
	case L2LinkMediumOPTICAL:
		return true
	case L2LinkMediumRF:
		return true
	default:
		return false
	}
}

// Defines values for L2LinkStatus.
const (
	L2LinkStatusDEGRADED L2LinkStatus = "DEGRADED"
	L2LinkStatusDOWN     L2LinkStatus = "DOWN"
	L2LinkStatusUNKNOWN  L2LinkStatus = "UNKNOWN"
	L2LinkStatusUP       L2LinkStatus = "UP"
)

// Valid indicates whether the value is a known member of the L2LinkStatus enum.
func (e L2LinkStatus) Valid() bool {
	switch e {
	case L2LinkStatusDEGRADED:
		return true
	case L2LinkStatusDOWN:
		return true
	case L2LinkStatusUNKNOWN:
		return true
	case L2LinkStatusUP:
		return true
	default:
		return false
	}
}

// Defines values for L3LogicalLinkType.
const (
	L3LogicalLinkTypeDIRECT  L3LogicalLinkType = "DIRECT"
	L3LogicalLinkTypeGENERIC L3LogicalLinkType = "GENERIC"
	L3LogicalLinkTypeOVERLAY L3LogicalLinkType = "OVERLAY"
	L3LogicalLinkTypeTUNNEL  L3LogicalLinkType = "TUNNEL"
)

// Valid indicates whether the value is a known member of the L3LogicalLinkType enum.
func (e L3LogicalLinkType) Valid() bool {
	switch e {
	case L3LogicalLinkTypeDIRECT:
		return true
	case L3LogicalLinkTypeGENERIC:
		return true
	case L3LogicalLinkTypeOVERLAY:
		return true
	case L3LogicalLinkTypeTUNNEL:
		return true
	default:
		return false
	}
}

// Defines values for L3PathDerived.
const (
	L3PathDerivedTrue L3PathDerived = true
)

// Valid indicates whether the value is a known member of the L3PathDerived enum.
func (e L3PathDerived) Valid() bool {
	switch e {
	case L3PathDerivedTrue:
		return true
	default:
		return false
	}
}

// Defines values for NamedFrameRefType.
const (
	FrameKindNamedFrame NamedFrameRefType = "NamedFrame"
)

// Valid indicates whether the value is a known member of the NamedFrameRefType enum.
func (e NamedFrameRefType) Valid() bool {
	switch e {
	case FrameKindNamedFrame:
		return true
	default:
		return false
	}
}

// Defines values for NodeNodeType.
const (
	NodeNodeTypeAIRCRAFT      NodeNodeType = "AIRCRAFT"
	NodeNodeTypeGENERIC       NodeNodeType = "GENERIC"
	NodeNodeTypeGROUNDSTATION NodeNodeType = "GROUND_STATION"
	NodeNodeTypeROUTER        NodeNodeType = "ROUTER"
	NodeNodeTypeSATELLITE     NodeNodeType = "SATELLITE"
	NodeNodeTypeSERVER        NodeNodeType = "SERVER"
	NodeNodeTypeSHIP          NodeNodeType = "SHIP"
	NodeNodeTypeSWITCH        NodeNodeType = "SWITCH"
	NodeNodeTypeTERMINAL      NodeNodeType = "TERMINAL"
	NodeNodeTypeUAV           NodeNodeType = "UAV"
	NodeNodeTypeVEHICLE       NodeNodeType = "VEHICLE"
)

// Valid indicates whether the value is a known member of the NodeNodeType enum.
func (e NodeNodeType) Valid() bool {
	switch e {
	case NodeNodeTypeAIRCRAFT:
		return true
	case NodeNodeTypeGENERIC:
		return true
	case NodeNodeTypeGROUNDSTATION:
		return true
	case NodeNodeTypeROUTER:
		return true
	case NodeNodeTypeSATELLITE:
		return true
	case NodeNodeTypeSERVER:
		return true
	case NodeNodeTypeSHIP:
		return true
	case NodeNodeTypeSWITCH:
		return true
	case NodeNodeTypeTERMINAL:
		return true
	case NodeNodeTypeUAV:
		return true
	case NodeNodeTypeVEHICLE:
		return true
	default:
		return false
	}
}

// Defines values for NodeBodyFrameRefType.
const (
	FrameKindNodeBodyFrame NodeBodyFrameRefType = "NodeBodyFrame"
)

// Valid indicates whether the value is a known member of the NodeBodyFrameRefType enum.
func (e NodeBodyFrameRefType) Valid() bool {
	switch e {
	case FrameKindNodeBodyFrame:
		return true
	default:
		return false
	}
}

// Defines values for OblateEllipsoidBodyShapeType.
const (
	BodyShapeOblateEllipsoid OblateEllipsoidBodyShapeType = "OblateEllipsoid"
)

// Valid indicates whether the value is a known member of the OblateEllipsoidBodyShapeType enum.
func (e OblateEllipsoidBodyShapeType) Valid() bool {
	switch e {
	case BodyShapeOblateEllipsoid:
		return true
	default:
		return false
	}
}

// Defines values for ObservationStampSampling.
const (
	SamplingExact    ObservationStampSampling = "Exact"
	SamplingNearest  ObservationStampSampling = "Nearest"
	SamplingPrevious ObservationStampSampling = "Previous"
)

// Valid indicates whether the value is a known member of the ObservationStampSampling enum.
func (e ObservationStampSampling) Valid() bool {
	switch e {
	case SamplingExact:
		return true
	case SamplingNearest:
		return true
	case SamplingPrevious:
		return true
	default:
		return false
	}
}

// Defines values for PhysicalWorldEnvironmentType.
const (
	PhysicalWorldEnvironmentTypeAIR         PhysicalWorldEnvironmentType = "AIR"
	PhysicalWorldEnvironmentTypeGENERIC     PhysicalWorldEnvironmentType = "GENERIC"
	PhysicalWorldEnvironmentTypeMIXED       PhysicalWorldEnvironmentType = "MIXED"
	PhysicalWorldEnvironmentTypeSEA         PhysicalWorldEnvironmentType = "SEA"
	PhysicalWorldEnvironmentTypeSPACE       PhysicalWorldEnvironmentType = "SPACE"
	PhysicalWorldEnvironmentTypeTERRESTRIAL PhysicalWorldEnvironmentType = "TERRESTRIAL"
)

// Valid indicates whether the value is a known member of the PhysicalWorldEnvironmentType enum.
func (e PhysicalWorldEnvironmentType) Valid() bool {
	switch e {
	case PhysicalWorldEnvironmentTypeAIR:
		return true
	case PhysicalWorldEnvironmentTypeGENERIC:
		return true
	case PhysicalWorldEnvironmentTypeMIXED:
		return true
	case PhysicalWorldEnvironmentTypeSEA:
		return true
	case PhysicalWorldEnvironmentTypeSPACE:
		return true
	case PhysicalWorldEnvironmentTypeTERRESTRIAL:
		return true
	default:
		return false
	}
}

// Defines values for ReachabilityEntryDerived.
const (
	ReachabilityEntryDerivedTrue ReachabilityEntryDerived = true
)

// Valid indicates whether the value is a known member of the ReachabilityEntryDerived enum.
func (e ReachabilityEntryDerived) Valid() bool {
	switch e {
	case ReachabilityEntryDerivedTrue:
		return true
	default:
		return false
	}
}

// Defines values for ResourceRefType.
const (
	ResourceRefTypeGENERIC     ResourceRefType = "GENERIC"
	ResourceRefTypeLINK        ResourceRefType = "LINK"
	ResourceRefTypeNODECOMPUTE ResourceRefType = "NODE_COMPUTE"
	ResourceRefTypeNODESTORAGE ResourceRefType = "NODE_STORAGE"
	ResourceRefTypeTERMINAL    ResourceRefType = "TERMINAL"
)

// Valid indicates whether the value is a known member of the ResourceRefType enum.
func (e ResourceRefType) Valid() bool {
	switch e {
	case ResourceRefTypeGENERIC:
		return true
	case ResourceRefTypeLINK:
		return true
	case ResourceRefTypeNODECOMPUTE:
		return true
	case ResourceRefTypeNODESTORAGE:
		return true
	case ResourceRefTypeTERMINAL:
		return true
	default:
		return false
	}
}

// Defines values for SatisfactionState.
const (
	SatisfactionStateInProgress SatisfactionState = "IN_PROGRESS"
	SatisfactionStateSatisfied  SatisfactionState = "SATISFIED"
	SatisfactionStateUnknown    SatisfactionState = "UNKNOWN"
	SatisfactionStateViolated   SatisfactionState = "VIOLATED"
)

// Valid indicates whether the value is a known member of the SatisfactionState enum.
func (e SatisfactionState) Valid() bool {
	switch e {
	case SatisfactionStateInProgress:
		return true
	case SatisfactionStateSatisfied:
		return true
	case SatisfactionStateUnknown:
		return true
	case SatisfactionStateViolated:
		return true
	default:
		return false
	}
}

// Defines values for ScenarioTimeUnit.
const (
	S ScenarioTimeUnit = "s"
)

// Valid indicates whether the value is a known member of the ScenarioTimeUnit enum.
func (e ScenarioTimeUnit) Valid() bool {
	switch e {
	case S:
		return true
	default:
		return false
	}
}

// Defines values for SchemaMetadataName.
const (
	SchemaMetadataNameNetworkWorldState SchemaMetadataName = "network-world-state"
)

// Valid indicates whether the value is a known member of the SchemaMetadataName enum.
func (e SchemaMetadataName) Valid() bool {
	switch e {
	case SchemaMetadataNameNetworkWorldState:
		return true
	default:
		return false
	}
}

// Defines values for SphereBodyShapeType.
const (
	BodyShapeSphere SphereBodyShapeType = "Sphere"
)

// Valid indicates whether the value is a known member of the SphereBodyShapeType enum.
func (e SphereBodyShapeType) Valid() bool {
	switch e {
	case BodyShapeSphere:
		return true
	default:
		return false
	}
}

// Defines values for TargetRefType.
const (
	TargetRefTypeGENERIC       TargetRefType = "GENERIC"
	TargetRefTypeINTENT        TargetRefType = "INTENT"
	TargetRefTypeLINK          TargetRefType = "LINK"
	TargetRefTypeNODE          TargetRefType = "NODE"
	TargetRefTypePHYSICALWORLD TargetRefType = "PHYSICAL_WORLD"
	TargetRefTypeTASK          TargetRefType = "TASK"
	TargetRefTypeTERMINAL      TargetRefType = "TERMINAL"
)

// Valid indicates whether the value is a known member of the TargetRefType enum.
func (e TargetRefType) Valid() bool {
	switch e {
	case TargetRefTypeGENERIC:
		return true
	case TargetRefTypeINTENT:
		return true
	case TargetRefTypeLINK:
		return true
	case TargetRefTypeNODE:
		return true
	case TargetRefTypePHYSICALWORLD:
		return true
	case TargetRefTypeTASK:
		return true
	case TargetRefTypeTERMINAL:
		return true
	default:
		return false
	}
}

// Defines values for TaskCompletionCriterion.
const (
	DESTINATIONACKNOWLEDGED TaskCompletionCriterion = "DESTINATION_ACKNOWLEDGED"
	DESTINATIONRECEIVED     TaskCompletionCriterion = "DESTINATION_RECEIVED"
	SOURCESENT              TaskCompletionCriterion = "SOURCE_SENT"
)

// Valid indicates whether the value is a known member of the TaskCompletionCriterion enum.
func (e TaskCompletionCriterion) Valid() bool {
	switch e {
	case DESTINATIONACKNOWLEDGED:
		return true
	case DESTINATIONRECEIVED:
		return true
	case SOURCESENT:
		return true
	default:
		return false
	}
}

// Defines values for TaskDeliveryMode.
const (
	BESTEFFORT    TaskDeliveryMode = "BEST_EFFORT"
	FIREANDFORGET TaskDeliveryMode = "FIRE_AND_FORGET"
	GUARANTEED    TaskDeliveryMode = "GUARANTEED"
)

// Valid indicates whether the value is a known member of the TaskDeliveryMode enum.
func (e TaskDeliveryMode) Valid() bool {
	switch e {
	case BESTEFFORT:
		return true
	case FIREANDFORGET:
		return true
	case GUARANTEED:
		return true
	default:
		return false
	}
}

// Defines values for TaskPriorityClass.
const (
	BACKGROUND      TaskPriorityClass = "BACKGROUND"
	EMERGENCY       TaskPriorityClass = "EMERGENCY"
	HIGH            TaskPriorityClass = "HIGH"
	MISSIONCRITICAL TaskPriorityClass = "MISSION_CRITICAL"
	NORMAL          TaskPriorityClass = "NORMAL"
)

// Valid indicates whether the value is a known member of the TaskPriorityClass enum.
func (e TaskPriorityClass) Valid() bool {
	switch e {
	case BACKGROUND:
		return true
	case EMERGENCY:
		return true
	case HIGH:
		return true
	case MISSIONCRITICAL:
		return true
	case NORMAL:
		return true
	default:
		return false
	}
}

// Defines values for TaskRequirementsLatencyConstraintType.
const (
	TaskRequirementsLatencyConstraintTypeHARD      TaskRequirementsLatencyConstraintType = "HARD"
	TaskRequirementsLatencyConstraintTypeOBJECTIVE TaskRequirementsLatencyConstraintType = "OBJECTIVE"
	TaskRequirementsLatencyConstraintTypeSOFT      TaskRequirementsLatencyConstraintType = "SOFT"
)

// Valid indicates whether the value is a known member of the TaskRequirementsLatencyConstraintType enum.
func (e TaskRequirementsLatencyConstraintType) Valid() bool {
	switch e {
	case TaskRequirementsLatencyConstraintTypeHARD:
		return true
	case TaskRequirementsLatencyConstraintTypeOBJECTIVE:
		return true
	case TaskRequirementsLatencyConstraintTypeSOFT:
		return true
	default:
		return false
	}
}

// Defines values for TaskRequirementsReliabilityConstraintType.
const (
	HARD      TaskRequirementsReliabilityConstraintType = "HARD"
	OBJECTIVE TaskRequirementsReliabilityConstraintType = "OBJECTIVE"
	SOFT      TaskRequirementsReliabilityConstraintType = "SOFT"
)

// Valid indicates whether the value is a known member of the TaskRequirementsReliabilityConstraintType enum.
func (e TaskRequirementsReliabilityConstraintType) Valid() bool {
	switch e {
	case HARD:
		return true
	case OBJECTIVE:
		return true
	case SOFT:
		return true
	default:
		return false
	}
}

// Defines values for TaskStateStatus.
const (
	TaskStateStatusCANCELLED TaskStateStatus = "CANCELLED"
	TaskStateStatusCOMPLETED TaskStateStatus = "COMPLETED"
	TaskStateStatusFAILED    TaskStateStatus = "FAILED"
	TaskStateStatusPAUSED    TaskStateStatus = "PAUSED"
	TaskStateStatusPENDING   TaskStateStatus = "PENDING"
	TaskStateStatusRUNNING   TaskStateStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the TaskStateStatus enum.
func (e TaskStateStatus) Valid() bool {
	switch e {
	case TaskStateStatusCANCELLED:
		return true
	case TaskStateStatusCOMPLETED:
		return true
	case TaskStateStatusFAILED:
		return true
	case TaskStateStatusPAUSED:
		return true
	case TaskStateStatusPENDING:
		return true
	case TaskStateStatusRUNNING:
		return true
	default:
		return false
	}
}

// Defines values for UniformRotationFrameTransformType.
const (
	FrameTransformUniformRotation UniformRotationFrameTransformType = "UniformRotation"
)

// Valid indicates whether the value is a known member of the UniformRotationFrameTransformType enum.
func (e UniformRotationFrameTransformType) Valid() bool {
	switch e {
	case FrameTransformUniformRotation:
		return true
	default:
		return false
	}
}

// Defines values for WorldEventEventType.
const (
	WorldEventEventTypeENVIRONMENTCHANGE WorldEventEventType = "ENVIRONMENT_CHANGE"
	WorldEventEventTypeGENERIC           WorldEventEventType = "GENERIC"
	WorldEventEventTypeINTERFERENCE      WorldEventEventType = "INTERFERENCE"
	WorldEventEventTypeLINKFAILURE       WorldEventEventType = "LINK_FAILURE"
	WorldEventEventTypeNODEFAILURE       WorldEventEventType = "NODE_FAILURE"
	WorldEventEventTypeTERMINALFAILURE   WorldEventEventType = "TERMINAL_FAILURE"
)

// Valid indicates whether the value is a known member of the WorldEventEventType enum.
func (e WorldEventEventType) Valid() bool {
	switch e {
	case WorldEventEventTypeENVIRONMENTCHANGE:
		return true
	case WorldEventEventTypeGENERIC:
		return true
	case WorldEventEventTypeINTERFERENCE:
		return true
	case WorldEventEventTypeLINKFAILURE:
		return true
	case WorldEventEventTypeNODEFAILURE:
		return true
	case WorldEventEventTypeTERMINALFAILURE:
		return true
	default:
		return false
	}
}

// Availability 某一个量或某一个实体的可观测性。这是本契约的一等语义：不可观测不得用 0、默认值或缺失字段表示，否则世界模型会把「没有观测」训练成真实值（例如把未采集的 CPU 利用率学成 0）。对应外部系统的 coverage / partial / unknown 语义；partial 既不代表失败，也不代表缺失值为 0。
type Availability struct {
	// CoverageRatio 该量在聚合范围内的覆盖率；1 表示完整覆盖。
	CoverageRatio *float32 `json:"coverage_ratio,omitempty"`

	// Partial true 表示结果基于部分可见数据得出，只能解释为部分统计，不能当作完整结论。
	Partial *bool `json:"partial,omitempty"`

	// Reason unavailable / unknown / partial 的原因标识，便于消费方区分「源不支持该量」与「暂时不可达」。
	Reason *string `json:"reason,omitempty"`

	// State observed=直接观测到；derived=由其他观测计算得到；unavailable=当前条件下不可观测；unknown=来源未声明。
	State AvailabilityState `json:"state"`
}

// AvailabilityState observed=直接观测到；derived=由其他观测计算得到；unavailable=当前条件下不可观测；unknown=来源未声明。
type AvailabilityState string

// BodyShape 天体形状。它同时是大地坐标的 datum：没有 shape 就无法解释经纬高。
type BodyShape struct {
	union json.RawMessage
}

// CartesianObservationFormat 笛卡尔位置格式：数值在 resolved_frame 轴中表达。
type CartesianObservationFormat struct {
	Type CartesianObservationFormatType `json:"type"`
}

// CartesianObservationFormatType defines model for CartesianObservationFormat.Type.
type CartesianObservationFormatType string

// CommunicationTerminalCapability 节点通信终端的能力描述。Laser、RF、Microwave、Ethernet、Optical 等统一使用该抽象。终端能力描述“能做什么”，当前工作状态放在 CommunicationTerminalState。
type CommunicationTerminalCapability struct {
	// AntennaGain 天线增益。
	AntennaGain *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"antenna_gain,omitempty"`

	// AntennaType 天线/光学口径等终端辐射/接收结构类型。
	AntennaType *string `json:"antenna_type,omitempty"`

	// Duplex 双工模式。
	Duplex *CommunicationTerminalCapabilityDuplex `json:"duplex,omitempty"`

	// Enabled 该能力对象是否在本场景中启用。
	Enabled bool `json:"enabled"`

	// Extensions 终端类型特有的扩展能力参数。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// FieldOfView 终端视场角。
	FieldOfView *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"field_of_view,omitempty"`

	// MaxDataRate 终端理论最大数据速率。
	MaxDataRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"max_data_rate"`

	// MaxRange 终端理论最大通信距离。
	MaxRange *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"max_range,omitempty"`

	// MaxTrackingRate 最大跟踪角速度。
	MaxTrackingRate *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"max_tracking_rate,omitempty"`

	// MaxTransmitPower 最大发射功率。
	MaxTransmitPower *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"max_transmit_power,omitempty"`

	// PointingRequired 是否要求定向指向或跟踪，例如激光终端通常为 true。
	PointingRequired *bool `json:"pointing_required,omitempty"`

	// SupportedBands 支持的频段名称或项目内部频段标识。
	SupportedBands *[]string `json:"supported_bands,omitempty"`

	// SupportedFrequencies 支持的中心频率或离散频点列表；需要频段时可结合 supported_bands。
	SupportedFrequencies *[]float32 `json:"supported_frequencies,omitempty"`

	// TerminalId 通信终端在所属节点内的唯一标识。
	TerminalId string `json:"terminal_id"`

	// TerminalType 通信终端类型。
	TerminalType CommunicationTerminalCapabilityTerminalType `json:"terminal_type"`
}

// CommunicationTerminalCapabilityDuplex 双工模式。
type CommunicationTerminalCapabilityDuplex string

// CommunicationTerminalCapabilityTerminalType 通信终端类型。
type CommunicationTerminalCapabilityTerminalType string

// CommunicationTerminalState 通信终端在当前 scenario_time 下的动态运行状态。
type CommunicationTerminalState struct {
	// Active 终端当前是否处于激活/工作状态。
	Active bool `json:"active"`

	// AngularVelocityBodyRadS 三维向量 [x, y, z]，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Vec3，语义保持一致。 单位由引用它的字段名声明显式声明（例如 _m、_m_s、_rad_s），不得依赖调用方推测。
	AngularVelocityBodyRadS *Vec3 `json:"angular_velocity_body_rad_s,omitempty"`

	// CurrentFrequency 当前工作频率。
	CurrentFrequency *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"current_frequency,omitempty"`

	// CurrentPower 当前发射功率。
	CurrentPower *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"current_power,omitempty"`

	// Operational 终端是否处于可工作状态。
	Operational bool `json:"operational"`

	// PointingDirection 当前指向信息；具体坐标表达由数据源决定。
	PointingDirection *map[string]interface{} `json:"pointing_direction,omitempty"`

	// RxRate 当前接收速率。
	RxRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"rx_rate"`

	// TerminalId 引用所属节点 capabilities.communication_terminals 中的 terminal_id。
	TerminalId string `json:"terminal_id"`

	// TxRate 当前发送速率。
	TxRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"tx_rate"`
}

// ComputeCapability 节点的静态或慢变化计算能力。
type ComputeCapability struct {
	// CpuComputeCapacity CPU 理论计算能力。
	CpuComputeCapacity *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"cpu_compute_capacity,omitempty"`

	// CpuCores CPU 逻辑/物理核心数，具体口径由数据源约定。
	CpuCores *int `json:"cpu_cores,omitempty"`

	// MemoryCapacity 内存总容量。
	MemoryCapacity *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"memory_capacity,omitempty"`
}

// Constraint defines model for Constraint.
type Constraint struct {
	// ConstraintType HARD=必须满足，SOFT=尽量满足，OBJECTIVE=优化方向。
	ConstraintType       ConstraintConstraintType `json:"constraint_type"`
	Enabled              bool                     `json:"enabled"`
	AdditionalProperties map[string]interface{}   `json:"-"`
}

// ConstraintConstraintType HARD=必须满足，SOFT=尽量满足，OBJECTIVE=优化方向。
type ConstraintConstraintType string

// ConsumerRef defines model for ConsumerRef.
type ConsumerRef struct {
	ConsumerId string `json:"consumer_id"`

	// Type 资源消费者类型。
	Type ConsumerRefType `json:"type"`
}

// ConsumerRefType 资源消费者类型。
type ConsumerRefType string

// DerivedMetrics 所有可由底层状态派生的聚合指标。
type DerivedMetrics struct {
	// Network 由基础状态计算得到、用于训练辅助任务、评估和可视化的网络级指标。
	Network NetworkDerivedMetrics `json:"network"`
	Tasks   TaskDerivedMetrics    `json:"tasks"`
}

// Destination L3 Reachability / Forwarding 的目的对象。
type Destination struct {
	// Type 目的对象类型。
	Type DestinationType `json:"type"`

	// Value node_id、IP prefix 或具体 IP address。
	Value string `json:"value"`
}

// DestinationType 目的对象类型。
type DestinationType string

// EnvironmentBody 环境天体：解释大地坐标所需的环境天体投影，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 EnvironmentBody，语义保持一致。 这是受限投影：只保留解释位置所需字段，gravity 与 atmosphere 由 Config 契约拥有，不在本契约重复定义（省略说明见 contracts/vendoring.yaml）。
type EnvironmentBody struct {
	// FixedFrame 参考系引用：命名参考系或场景实体机体系，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 FrameRef，语义保持一致。 任何坐标都必须能通过 FrameRef 独立解释；不得从字段名、实体名或调用方类型猜测参考系。
	FixedFrame FrameRef `json:"fixed_frame"`

	// InertialFrame 参考系引用：命名参考系或场景实体机体系，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 FrameRef，语义保持一致。 任何坐标都必须能通过 FrameRef 独立解释；不得从字段名、实体名或调用方类型猜测参考系。
	InertialFrame FrameRef `json:"inertial_frame"`

	// Name 场景内稳定的环境天体标识；同一场景内唯一。
	Name string `json:"name"`

	// Shape 天体形状。它同时是大地坐标的 datum：没有 shape 就无法解释经纬高。
	Shape BodyShape `json:"shape"`
}

// EphemerisFrameTransform 星历变换：参考系变换由版本化 provider 按时刻求值。provider 缺失、超出覆盖范围或输出非有限值时必须整体失败，不得回退到上一帧。
type EphemerisFrameTransform struct {
	// DerivativeOrder 导数阶数约定。
	DerivativeOrder string `json:"derivative_order"`

	// Observer 观察者标识。
	Observer string `json:"observer"`

	// Orientation 姿态表达约定。
	Orientation *string `json:"orientation,omitempty"`

	// Provider 版本化空间 provider 的名称。
	Provider string `json:"provider"`

	// Target 目标标识。
	Target string                      `json:"target"`
	Type   EphemerisFrameTransformType `json:"type"`
}

// EphemerisFrameTransformType defines model for EphemerisFrameTransform.Type.
type EphemerisFrameTransformType string

// ExternalAction 从 Network World Model 系统边界之外主动施加的干预。一次 Action 发生后，其影响应反映在后续 World State 中。
type ExternalAction struct {
	ActionId string `json:"action_id"`

	// ActionType 外部主动干预类型。
	ActionType ExternalActionActionType `json:"action_type"`

	// ExecutedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ExecutedAt ScenarioTime `json:"executed_at"`

	// Parameters Action 特有参数。例如 TASK_SUBMIT 可包含 task 定义，INTENT_CHANGE 可包含新的 intent 字段。
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Target     TargetRef               `json:"target"`
}

// ExternalActionActionType 外部主动干预类型。
type ExternalActionActionType string

// FixedFrameTransform 固定刚体变换：子参考系相对父参考系为常量平移与旋转。
type FixedFrameTransform struct {
	// RotationChildToParentXyzw 单位四元数 [x, y, z, w]（标量在最后），vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 QuaternionXYZW，语义保持一致。 表示从字段名所指 source frame 到 target frame 的主动旋转；分量顺序固定为 XYZW，禁止使用 wxyz 顺序。
	RotationChildToParentXyzw QuaternionXYZW `json:"rotation_child_to_parent_xyzw"`

	// TranslationParentM 三维向量 [x, y, z]，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Vec3，语义保持一致。 单位由引用它的字段名声明显式声明（例如 _m、_m_s、_rad_s），不得依赖调用方推测。
	TranslationParentM Vec3                    `json:"translation_parent_m"`
	Type               FixedFrameTransformType `json:"type"`
}

// FixedFrameTransformType defines model for FixedFrameTransform.Type.
type FixedFrameTransformType string

// Flow 由 Traffic Demand 实际形成的网络传输流。
type Flow struct {
	DemandId        *string `json:"demand_id,omitempty"`
	DestinationNode string  `json:"destination_node"`
	FlowId          string  `json:"flow_id"`

	// PathId 可选引用当前派生 Path。
	PathId     *string `json:"path_id,omitempty"`
	SourceNode string  `json:"source_node"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`

	// State 实际网络流在当前 scenario_time 下的状态。
	State  FlowState `json:"state"`
	TaskId *string   `json:"task_id,omitempty"`

	// TransportType 传输类型；仅作为 Flow 特征，不绑定模型结构。
	TransportType FlowTransportType `json:"transport_type"`
}

// FlowTransportType 传输类型；仅作为 Flow 特征，不绑定模型结构。
type FlowTransportType string

// FlowState 实际网络流在当前 scenario_time 下的状态。
type FlowState struct {
	// ActualThroughput 实际有效吞吐。
	ActualThroughput struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"actual_throughput"`

	// AllocatedRate 网络为该 Flow 分配的速率/带宽。
	AllocatedRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"allocated_rate"`

	// BytesDelivered 目的端已经成功接收的字节数。
	BytesDelivered struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_delivered"`

	// BytesRemaining 剩余待发送/待完成字节数。
	BytesRemaining *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"bytes_remaining,omitempty"`

	// BytesSent 源端已经发送的字节数。
	BytesSent struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_sent"`

	// BytesTotal Flow 总字节数。
	BytesTotal *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"bytes_total,omitempty"`
	LossRate float32 `json:"loss_rate"`

	// OfferedRate 数据源实际尝试发送的速率。
	OfferedRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"offered_rate"`

	// Rtt 往返时延。
	Rtt *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"rtt,omitempty"`

	// Status Flow 生命周期状态。
	Status FlowStateStatus `json:"status"`
}

// FlowStateStatus Flow 生命周期状态。
type FlowStateStatus string

// ForwardingEntry 协议无关的 L3 转发结果。记录当前实际上如何转发，不记录 OSPF/BGP/IS-IS 等机制如何得到该结果。
type ForwardingEntry struct {
	// Destination L3 Reachability / Forwarding 的目的对象。
	Destination Destination `json:"destination"`

	// ForwardingId Forwarding Entry 唯一 ID。
	ForwardingId string `json:"forwarding_id"`

	// NextHops 有效下一跳集合。
	NextHops []NextHop `json:"next_hops"`

	// NodeId 执行该转发决策的节点。
	NodeId string `json:"node_id"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`

	// ValidFrom 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ValidFrom ScenarioTime `json:"valid_from"`

	// ValidUntil 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ValidUntil *ScenarioTime `json:"valid_until,omitempty"`
}

// FrameRef 参考系引用：命名参考系或场景实体机体系，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 FrameRef，语义保持一致。 任何坐标都必须能通过 FrameRef 独立解释；不得从字段名、实体名或调用方类型猜测参考系。
type FrameRef struct {
	union json.RawMessage
}

// FrameTransform 参考系变换链上的一环，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 FrameTransform，语义保持一致。
type FrameTransform struct {
	union json.RawMessage
}

// GeodeticObservationFormat 大地位置格式：必须声明环境天体，datum 由该天体的 shape 解析。大地坐标只允许与该天体的固定参考系组合；不得在惯性系或机体系上返回大地坐标。
type GeodeticObservationFormat struct {
	// Body 场景内稳定的环境天体标识；同一场景内唯一。
	Body string                        `json:"body"`
	Type GeodeticObservationFormatType `json:"type"`
}

// GeodeticObservationFormatType defines model for GeodeticObservationFormat.Type.
type GeodeticObservationFormatType string

// IPAddress L3 地址信息。
type IPAddress struct {
	// Address IPv4 或 IPv6 地址字符串。
	Address string `json:"address"`

	// Family 地址族。
	Family IPAddressFamily `json:"family"`

	// PrefixLength 前缀长度。
	PrefixLength int `json:"prefix_length"`

	// Primary 是否为该 L3 接口主地址。
	Primary bool `json:"primary"`
}

// IPAddressFamily 地址族。
type IPAddressFamily string

// IdentityFrameTransform 恒等变换：子参考系与父参考系同向同原点。
type IdentityFrameTransform struct {
	Type IdentityFrameTransformType `json:"type"`
}

// IdentityFrameTransformType defines model for IdentityFrameTransform.Type.
type IdentityFrameTransformType string

// Instant 绝对时刻 + 时间尺度，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Instant，语义保持一致。 value 是不带时区后缀的扩展 ISO-8601，scale 单独决定时间尺度。 世界模型自身的内部时间轴仍是 scenario_time；Instant 只用于把观测锚定到外部系统的绝对时间，二者通过 TimeBase 换算。
type Instant struct {
	// Scale 时间尺度。UTC=协调世界时；TAI=国际原子时；TT=地球时；TDB=太阳系质心力学时。没有 scale 的时刻无法被独立解释。
	Scale InstantScale `json:"scale"`

	// Value 不带时区后缀的扩展 ISO-8601 时刻 YYYY-MM-DDThh:mm:ss[.fraction]；秒值 60 只允许用于经版本化 leap-second 数据验证后的 UTC。
	Value string `json:"value"`
}

// InstantScale 时间尺度。UTC=协调世界时；TAI=国际原子时；TT=地球时；TDB=太阳系质心力学时。没有 scale 的时刻无法被独立解释。
type InstantScale string

// L2Endpoint L2 Link 的端点。必须同时指向 Node 和该 Node 上的通信终端。
type L2Endpoint struct {
	// NodeId 引用 nodes[].node_id。
	NodeId string `json:"node_id"`

	// TerminalId 引用对应节点的 communication terminal。
	TerminalId string `json:"terminal_id"`
}

// L2Link 两个通信终端之间当前存在的二层/通信层连接状态。星间、星地、地面、空地等统一建模。
type L2Link struct {
	// Availability 某一个量或某一个实体的可观测性。这是本契约的一等语义：不可观测不得用 0、默认值或缺失字段表示，否则世界模型会把「没有观测」训练成真实值（例如把未采集的 CPU 利用率学成 0）。对应外部系统的 coverage / partial / unknown 语义；partial 既不代表失败，也不代表缺失值为 0。
	Availability *Availability `json:"availability,omitempty"`

	// AvailableBandwidth 当前可用带宽。
	AvailableBandwidth struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"available_bandwidth"`

	// BitErrorRate 可选比特误码率，0~1。
	BitErrorRate *float32 `json:"bit_error_rate,omitempty"`

	// Capacity 当前有效容量。
	Capacity struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"capacity"`

	// Enabled 该 Link 是否属于当前场景配置。
	Enabled bool `json:"enabled"`

	// EndpointA L2 Link 的端点。必须同时指向 Node 和该 Node 上的通信终端。
	EndpointA L2Endpoint `json:"endpoint_a"`

	// EndpointB L2 Link 的端点。必须同时指向 Node 和该 Node 上的通信终端。
	EndpointB L2Endpoint `json:"endpoint_b"`

	// Extensions 链路扩展字段。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// Jitter 时延抖动。
	Jitter struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"jitter"`

	// LinkClass 场景语义上的链路分类。
	LinkClass L2LinkLinkClass `json:"link_class"`

	// LinkId L2 Link 全局唯一标识。
	LinkId string `json:"link_id"`

	// Medium 实际通信媒介。
	Medium L2LinkMedium `json:"medium"`

	// PacketLossRate 包丢失率，0~1。
	PacketLossRate float32 `json:"packet_loss_rate"`

	// PropagationDelay 传播时延。
	PropagationDelay struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"propagation_delay"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`

	// Status 链路当前运行状态。
	Status L2LinkStatus `json:"status"`

	// ThroughputBps 链路当前实际传输吞吐量 (bit/s)。与 capacity 配合用于计算利用率与评估拥塞。
	ThroughputBps *float32 `json:"throughput_bps,omitempty"`

	// TransmissionDelay 发送/序列化时延。
	TransmissionDelay *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"transmission_delay,omitempty"`

	// Utilization 当前利用率。通常建议 0~1；允许数据源保留>1以表达过载时需在导入规范中明确。
	Utilization float32 `json:"utilization"`
}

// L2LinkLinkClass 场景语义上的链路分类。
type L2LinkLinkClass string

// L2LinkMedium 实际通信媒介。
type L2LinkMedium string

// L2LinkStatus 链路当前运行状态。
type L2LinkStatus string

// L2Network 当前 scenario_time 下的通信/L2 网络。
type L2Network struct {
	Links []L2Link `json:"links"`
}

// L3AggregateState 由 L3 状态派生得到的宏观网络指标。
type L3AggregateState struct {
	// ConnectedComponents 当前三层连通分量数量。
	ConnectedComponents *int `json:"connected_components,omitempty"`

	// IsolatedNodes 当前孤立节点 ID。
	IsolatedNodes *[]string `json:"isolated_nodes,omitempty"`

	// ReachablePairRatio 可达节点对比例。
	ReachablePairRatio *float32 `json:"reachable_pair_ratio,omitempty"`
}

// L3Interface 节点上的三层逻辑接口。可关联底层通信终端。
type L3Interface struct {
	Addresses []IPAddress `json:"addresses"`

	// Enabled 接口是否启用。
	Enabled bool `json:"enabled"`

	// L3InterfaceId L3 接口全局唯一 ID。
	L3InterfaceId string `json:"l3_interface_id"`

	// NodeId 所属节点 ID。
	NodeId string `json:"node_id"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`

	// TerminalId 可选关联的 L2/通信终端 ID。
	TerminalId *string `json:"terminal_id,omitempty"`
}

// L3LogicalEndpoint defines model for L3LogicalEndpoint.
type L3LogicalEndpoint struct {
	L3InterfaceId string `json:"l3_interface_id"`
	NodeId        string `json:"node_id"`
}

// L3LogicalLink 协议无关的三层逻辑直接连接。它不是 OSPF/BGP 邻居关系，可代表 DIRECT、TUNNEL、OVERLAY 等逻辑连接。
type L3LogicalLink struct {
	EndpointA L3LogicalEndpoint `json:"endpoint_a"`
	EndpointB L3LogicalEndpoint `json:"endpoint_b"`

	// LogicalLinkId 三层逻辑链路唯一 ID。
	LogicalLinkId string `json:"logical_link_id"`

	// Operational 逻辑链路当前是否有效。
	Operational bool `json:"operational"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`

	// Type 三层逻辑连接类型。
	Type L3LogicalLinkType `json:"type"`
}

// L3LogicalLinkType 三层逻辑连接类型。
type L3LogicalLinkType string

// L3Network 协议无关的 L3 Network State。
type L3Network struct {
	// AggregateState 由 L3 状态派生得到的宏观网络指标。
	AggregateState    *L3AggregateState       `json:"aggregate_state,omitempty"`
	Extensions        *map[string]interface{} `json:"extensions,omitempty"`
	ForwardingEntries []ForwardingEntry       `json:"forwarding_entries"`
	Interfaces        []L3Interface           `json:"interfaces"`
	LogicalLinks      []L3LogicalLink         `json:"logical_links"`
}

// L3Path 根据 Forwarding State 派生得到的端到端路径。
type L3Path struct {
	Derived         L3PathDerived `json:"derived"`
	DestinationNode string        `json:"destination_node"`
	LogicalLinks    []string      `json:"logical_links"`

	// Metrics 由 Path 与底层 Link/Traffic 状态推导出的端到端路径指标。
	Metrics    PathMetrics `json:"metrics"`
	Nodes      []string    `json:"nodes"`
	PathId     string      `json:"path_id"`
	SourceNode string      `json:"source_node"`
	Valid      bool        `json:"valid"`
}

// L3PathDerived defines model for L3Path.Derived.
type L3PathDerived bool

// NamedFrameRef 对场景声明的命名参考系的引用。
type NamedFrameRef struct {
	// Name 场景内稳定的命名参考系标识；同一场景内唯一，且不得使用显示名。
	Name string `json:"name"`

	// Type 引用种类判别字段。
	Type NamedFrameRefType `json:"type"`
}

// NamedFrameRefType 引用种类判别字段。
type NamedFrameRefType string

// NetworkDerivedMetrics 由基础状态计算得到、用于训练辅助任务、评估和可视化的网络级指标。
type NetworkDerivedMetrics struct {
	AveragePathLength *float32 `json:"average_path_length,omitempty"`

	// AverageRtt 全网平均 RTT。
	AverageRtt *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"average_rtt,omitempty"`
	CongestedLinkCount     *int     `json:"congested_link_count,omitempty"`
	MaximumLinkUtilization *float32 `json:"maximum_link_utilization,omitempty"`
	PacketLossRate         *float32 `json:"packet_loss_rate,omitempty"`

	// Paths 由转发状态推导得到的端到端路径集合（派生状态）。
	Paths *[]L3Path `json:"paths,omitempty"`

	// Reachability 由转发状态推导得到的端到端可达性集合（派生状态）。
	Reachability       *[]ReachabilityEntry `json:"reachability,omitempty"`
	ReachablePairRatio *float32             `json:"reachable_pair_ratio,omitempty"`
}

// NetworkIntent 网络系统当前的高层目标和任务保障倾向。它不描述具体控制协议，而作为内部 Network Dynamics 的条件。
type NetworkIntent struct {
	Connectivity struct {
		Enabled bool `json:"enabled"`

		// MinimumReachablePairRatio 可选最低全局可达节点对比例。
		MinimumReachablePairRatio  *float32 `json:"minimum_reachable_pair_ratio,omitempty"`
		PreserveGlobalConnectivity bool     `json:"preserve_global_connectivity"`
	} `json:"connectivity"`
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// ObjectiveWeights 可选高层目标权重，可用于条件化世界模型或后续控制研究。
	ObjectiveWeights *struct {
		Connectivity       *float32 `json:"connectivity,omitempty"`
		Latency            *float32 `json:"latency,omitempty"`
		Reliability        *float32 `json:"reliability,omitempty"`
		ResourceEfficiency *float32 `json:"resource_efficiency,omitempty"`
		TaskAssurance      *float32 `json:"task_assurance,omitempty"`
	} `json:"objective_weights,omitempty"`
	ResourceEfficiency struct {
		AvoidCongestion bool `json:"avoid_congestion"`
		Enabled         bool `json:"enabled"`
		LoadBalance     bool `json:"load_balance"`
	} `json:"resource_efficiency"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp         *ObservationStamp `json:"stamp,omitempty"`
	TaskAssurance struct {
		Enabled           bool `json:"enabled"`
		PreemptionAllowed bool `json:"preemption_allowed"`
		PriorityAware     bool `json:"priority_aware"`
		RespectTaskQos    bool `json:"respect_task_qos"`
	} `json:"task_assurance"`
}

// NetworkState 内生通信网络完整拓扑、资源、业务、事件与动作的高频运行状态。
type NetworkState struct {
	// DerivedMetrics 所有可由底层状态派生的聚合指标。
	DerivedMetrics *DerivedMetrics `json:"derived_metrics,omitempty"`

	// Events 与当前快照相关、在该时间窗口内发生的 Event。
	Events []WorldEvent `json:"events"`

	// ExternalActions 与当前快照相关、在该时间窗口内发生的外部主动 Action。
	ExternalActions []ExternalAction `json:"external_actions"`

	// L2Network 当前 scenario_time 下的通信/L2 网络。
	L2Network L2Network `json:"l2_network"`

	// L3Network 协议无关的 L3 Network State。
	L3Network L3Network `json:"l3_network"`

	// NetworkIntent 网络系统当前的高层目标和任务保障倾向。它不描述具体控制协议，而作为内部 Network Dynamics 的条件。
	NetworkIntent   NetworkIntent   `json:"network_intent"`
	Nodes           []Node          `json:"nodes"`
	Tasks           []Task          `json:"tasks"`
	TrafficResource TrafficResource `json:"traffic_resource"`
}

// NetworkWorldState Network World State 顶层快照信封对象。承载全局元数据、时间基准、数据血缘与可观测性，封装内部的世界状态本体。
type NetworkWorldState struct {
	// Availability 某一个量或某一个实体的可观测性。这是本契约的一等语义：不可观测不得用 0、默认值或缺失字段表示，否则世界模型会把「没有观测」训练成真实值（例如把未采集的 CPU 利用率学成 0）。对应外部系统的 coverage / partial / unknown 语义；partial 既不代表失败，也不代表缺失值为 0。
	Availability *Availability `json:"availability,omitempty"`

	// Extensions 顶层扩展字段。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// Provenance 该快照的数据来源。数据血缘必须能从快照本身读出，不能依赖外部记录；否则异步数据源的对齐结果无法审计，数据集也无法精确复现。
	Provenance *Provenance `json:"provenance,omitempty"`

	// ScenarioTime 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ScenarioTime ScenarioTime `json:"scenario_time"`

	// Schema 标识当前 Network World State 数据契约的名称和版本。
	Schema SchemaMetadata `json:"schema"`

	// SnapshotId 当前 World Snapshot 唯一标识。
	SnapshotId string `json:"snapshot_id"`

	// State 网络与物理世界的动态状态本体容器，与外部信封元数据解耦。
	State WorldState `json:"state"`

	// TimeBase 把世界模型的内部时间轴（scenario_time，相对秒）锚定到外部系统的绝对时刻。该绑定在一个场景内唯一且不变，否则 ObservationStamp 中的 Instant 无法与scenario_time 互相换算。缺少该绑定的快照不能声称自己能独立解释观测时刻。
	TimeBase *TimeBase `json:"time_base,omitempty"`

	// WorldId 场景/世界唯一标识。
	WorldId string `json:"world_id"`
}

// NextHop 当前节点针对指定目的的实际下一跳。用于表达单路径、ECMP 或加权多路径。
type NextHop struct {
	// L3InterfaceId 出接口。
	L3InterfaceId string `json:"l3_interface_id"`

	// NodeId 下一跳节点。
	NodeId string `json:"node_id"`

	// Weight 多路径权重。单路径通常为 1。
	Weight float32 `json:"weight"`
}

// Node 网络世界中的独立物理设备或平台。卫星、地面站、飞机、无人机、车辆、舰船、服务器等统一建模为 Node。
type Node struct {
	// Capabilities 节点作为独立硬件个体所具备的静态/慢变化能力集合。
	Capabilities NodeCapabilities `json:"capabilities"`

	// Enabled 节点是否属于当前场景。
	Enabled bool `json:"enabled"`

	// Extensions 节点级扩展字段。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// Name 可读名称。
	Name *string `json:"name,omitempty"`

	// NodeId 在 world_id 范围内全局唯一的节点 ID。
	NodeId string `json:"node_id"`

	// NodeType 节点类型。该枚举用于分类，不应驱动核心模型中的场景特化逻辑。
	NodeType NodeNodeType `json:"node_type"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`

	// State 节点在当前 scenario_time 下的动态状态。
	State NodeState `json:"state"`
}

// NodeNodeType 节点类型。该枚举用于分类，不应驱动核心模型中的场景特化逻辑。
type NodeNodeType string

// NodeBodyFrameRef 对某个场景实体机体系的引用。使用被引用实体在同一时刻的姿态；引用产生的姿态依赖参与位姿依赖图，不允许用上一 tick 的姿态打破环。
type NodeBodyFrameRef struct {
	// Node 场景实体的稳定名称。
	Node string `json:"node"`

	// Type 引用种类判别字段。
	Type NodeBodyFrameRefType `json:"type"`
}

// NodeBodyFrameRefType 引用种类判别字段。
type NodeBodyFrameRefType string

// NodeCapabilities 节点作为独立硬件个体所具备的静态/慢变化能力集合。
type NodeCapabilities struct {
	CommunicationTerminals []CommunicationTerminalCapability `json:"communication_terminals"`

	// Compute 节点的静态或慢变化计算能力。
	Compute *ComputeCapability `json:"compute,omitempty"`

	// Extensions 节点特有能力扩展。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// StorageCapacity 节点本地存储总容量。
	StorageCapacity *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"storage_capacity,omitempty"`
}

// NodeState 节点在当前 scenario_time 下的动态状态。
type NodeState struct {
	// AngularVelocityBodyRadS 三维向量 [x, y, z]，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Vec3，语义保持一致。 单位由引用它的字段名声明显式声明（例如 _m、_m_s、_rad_s），不得依赖调用方推测。
	AngularVelocityBodyRadS *Vec3 `json:"angular_velocity_body_rad_s,omitempty"`

	// Availability 某一个量或某一个实体的可观测性。这是本契约的一等语义：不可观测不得用 0、默认值或缺失字段表示，否则世界模型会把「没有观测」训练成真实值（例如把未采集的 CPU 利用率学成 0）。对应外部系统的 coverage / partial / unknown 语义；partial 既不代表失败，也不代表缺失值为 0。
	Availability           *Availability                `json:"availability,omitempty"`
	CommunicationTerminals []CommunicationTerminalState `json:"communication_terminals"`

	// CpuUtilization CPU 利用率，统一使用 0~1。
	CpuUtilization *float32 `json:"cpu_utilization,omitempty"`

	// Extensions 节点动态状态扩展。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// Faults 当前生效的故障/异常标识。
	Faults *[]string `json:"faults,omitempty"`

	// MemoryUtilization 内存利用率，统一使用 0~1。
	MemoryUtilization *float32 `json:"memory_utilization,omitempty"`

	// Operational 节点整体是否处于工作状态。
	Operational bool `json:"operational"`

	// Orientation 节点姿态。对需要指向、波束、平台姿态等场景有意义。
	Orientation *Orientation `json:"orientation,omitempty"`

	// Position 节点在当前 scenario_time 下的位置状态。位置属于 Node State，而不是 Physical World。
	Position Position `json:"position"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`

	// Velocity 节点在当前 scenario_time 下相对于 position.frame 的速度。
	Velocity Velocity `json:"velocity"`
}

// OblateEllipsoidBodyShape 扁椭球天体形状，用于表达 WGS84 之类的参考椭球。
type OblateEllipsoidBodyShape struct {
	// InverseFlattening 扁率倒数 1/f。
	InverseFlattening float64 `json:"inverse_flattening"`

	// SemiMajorAxisM 长半轴，单位为米。
	SemiMajorAxisM float64                      `json:"semi_major_axis_m"`
	Type           OblateEllipsoidBodyShapeType `json:"type"`
}

// OblateEllipsoidBodyShapeType defines model for OblateEllipsoidBodyShape.Type.
type OblateEllipsoidBodyShapeType string

// ObservationPositionFormat 位置表达格式，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 ObservationPositionFormat，语义保持一致。 消费方必须按 response 中解析后的格式解释数值，不得把任意笛卡尔坐标自动当作地球固连坐标。
type ObservationPositionFormat struct {
	union json.RawMessage
}

// ObservationStamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
type ObservationStamp struct {
	// ObservedAtInstant 绝对时刻 + 时间尺度，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Instant，语义保持一致。 value 是不带时区后缀的扩展 ISO-8601，scale 单独决定时间尺度。 世界模型自身的内部时间轴仍是 scenario_time；Instant 只用于把观测锚定到外部系统的绝对时间，二者通过 TimeBase 换算。
	ObservedAtInstant *Instant `json:"observed_at_instant,omitempty"`

	// ObservedAtScenarioTime 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ObservedAtScenarioTime *ScenarioTime `json:"observed_at_scenario_time,omitempty"`

	// Sampling 该观测相对请求时刻的采样策略。Replay 场景必须显式声明，不允许由 adapter 自行选择，否则回放结果不可复现。
	Sampling *ObservationStampSampling `json:"sampling,omitempty"`

	// SourceRecordId 源系统内部的记录标识，不要求全局唯一。
	SourceRecordId *string `json:"source_record_id,omitempty"`

	// SourceSystem 产生该观测的外部系统名称。
	SourceSystem string `json:"source_system"`

	// ValidFrom 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ValidFrom *ScenarioTime `json:"valid_from,omitempty"`

	// ValidUntil 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ValidUntil *ScenarioTime `json:"valid_until,omitempty"`
}

// ObservationStampSampling 该观测相对请求时刻的采样策略。Replay 场景必须显式声明，不允许由 adapter 自行选择，否则回放结果不可复现。
type ObservationStampSampling string

// Orientation 节点姿态。对需要指向、波束、平台姿态等场景有意义。
type Orientation struct {
	// Pitch 俯仰角。
	Pitch *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"pitch,omitempty"`

	// Roll 横滚角。
	Roll *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"roll,omitempty"`

	// Yaw 偏航角。
	Yaw *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"yaw,omitempty"`
}

// PathMetrics 由 Path 与底层 Link/Traffic 状态推导出的端到端路径指标。
type PathMetrics struct {
	// BottleneckCapacity 路径瓶颈容量。
	BottleneckCapacity struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bottleneck_capacity"`
	HopCount       int     `json:"hop_count"`
	PacketLossRate float32 `json:"packet_loss_rate"`

	// TotalDelay 端到端总时延。
	TotalDelay struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"total_delay"`
}

// PhysicalWorld 节点之外客观存在的物理环境。用于描述空间、地理、大气、电磁、干扰及传播环境。节点的位置、速度、姿态等属于 Node State。
type PhysicalWorld struct {
	// Atmosphere 大气环境条件。可由仿真系统直接采集并映射。
	Atmosphere *struct {
		// CloudAttenuation 云衰减。
		CloudAttenuation *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"cloud_attenuation,omitempty"`

		// Humidity 相对湿度，建议使用 0~1。
		Humidity *float32 `json:"humidity,omitempty"`

		// Pressure 环境气压。
		Pressure *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"pressure,omitempty"`

		// RainRate 降雨率。
		RainRate *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"rain_rate,omitempty"`

		// Temperature 环境温度。
		Temperature *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"temperature,omitempty"`
	} `json:"atmosphere,omitempty"`

	// ElectromagneticEnvironment 电磁背景、噪声和干扰环境。
	ElectromagneticEnvironment *struct {
		// BackgroundNoise 背景噪声功率。
		BackgroundNoise *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"background_noise,omitempty"`

		// InterferenceRegions 场景中的干扰区域或干扰源集合。
		InterferenceRegions *[]struct {
			// Description 干扰源的人类可读说明。
			Description *string `json:"description,omitempty"`

			// InterferenceId 干扰对象唯一标识。
			InterferenceId string `json:"interference_id"`

			// Parameters 由数据源提供的干扰参数。Schema 对其保持开放。
			Parameters *map[string]interface{} `json:"parameters,omitempty"`
		} `json:"interference_regions,omitempty"`
	} `json:"electromagnetic_environment,omitempty"`

	// EnvironmentType 场景的宏观物理环境分类，仅用于描述和筛选，不决定核心计算逻辑。
	EnvironmentType PhysicalWorldEnvironmentType `json:"environment_type"`

	// Extensions 物理世界的扩展属性。扩展字段不应改变核心 Schema 语义。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// SpatialEnvironment 空间/地理参考环境。
	SpatialEnvironment struct {
		// DefaultReferenceFrame 参考系引用：命名参考系或场景实体机体系，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 FrameRef，语义保持一致。 任何坐标都必须能通过 FrameRef 独立解释；不得从字段名、实体名或调用方类型猜测参考系。
		DefaultReferenceFrame FrameRef `json:"default_reference_frame"`

		// EarthModel 地球模型或参考椭球，例如 WGS84。
		EarthModel *string `json:"earth_model,omitempty"`

		// ObstacleModelId 外部障碍物模型标识。
		ObstacleModelId *string `json:"obstacle_model_id,omitempty"`

		// TerrainModelId 外部地形模型标识。
		TerrainModelId *string `json:"terrain_model_id,omitempty"`
	} `json:"spatial_environment"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`
}

// PhysicalWorldEnvironmentType 场景的宏观物理环境分类，仅用于描述和筛选，不决定核心计算逻辑。
type PhysicalWorldEnvironmentType string

// Position 节点在当前 scenario_time 下的位置状态。位置属于 Node State，而不是 Physical World。
type Position struct {
	// Frame 参考系引用：命名参考系或场景实体机体系，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 FrameRef，语义保持一致。 任何坐标都必须能通过 FrameRef 独立解释；不得从字段名、实体名或调用方类型猜测参考系。
	Frame FrameRef `json:"frame"`

	// X X 轴坐标。
	X struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"x"`

	// Y Y 轴坐标。
	Y struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"y"`

	// Z Z 轴坐标。
	Z struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"z"`
}

// Provenance 该快照的数据来源。数据血缘必须能从快照本身读出，不能依赖外部记录；否则异步数据源的对齐结果无法审计，数据集也无法精确复现。
type Provenance struct {
	// Adapter 执行映射的 adapter 名称。
	Adapter *string `json:"adapter,omitempty"`

	// AdapterVersion 映射规范（mapping spec）的名称与版本；用于精确复现数据集。
	AdapterVersion *string `json:"adapter_version,omitempty"`

	// ImportedAt 导入发生的墙上时钟时间；仅用于审计，不参与任何计算。
	ImportedAt *time.Time `json:"imported_at,omitempty"`
	Notes      *string    `json:"notes,omitempty"`

	// RawSourceRefs 原始文件或流的引用（路径、URI 或对象名）。
	RawSourceRefs *[]string `json:"raw_source_refs,omitempty"`

	// SimulationRunId 外部仿真系统的运行标识。
	SimulationRunId *string `json:"simulation_run_id,omitempty"`

	// SourceRecordIds 参与该快照的原始记录标识。
	SourceRecordIds *[]string `json:"source_record_ids,omitempty"`

	// SourceSystem 产生原始数据的外部系统名称。
	SourceSystem string `json:"source_system"`
}

// QuaternionXYZW 单位四元数 [x, y, z, w]（标量在最后），vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 QuaternionXYZW，语义保持一致。 表示从字段名所指 source frame 到 target frame 的主动旋转；分量顺序固定为 XYZW，禁止使用 wxyz 顺序。
type QuaternionXYZW = []float64

// ReachabilityEntry 从一个源节点到一个 L3 目的对象的可达性。通常可以作为 Derived State。
type ReachabilityEntry struct {
	// Derived 标识该记录为派生状态。
	Derived ReachabilityEntryDerived `json:"derived"`

	// Destination L3 Reachability / Forwarding 的目的对象。
	Destination Destination `json:"destination"`
	Reachable   bool        `json:"reachable"`
	SourceNode  string      `json:"source_node"`
}

// ReachabilityEntryDerived 标识该记录为派生状态。
type ReachabilityEntryDerived bool

// ReferenceFrame 场景声明的命名参考系，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 ReferenceFrame，语义保持一致。 parent 与 transform 共同把它连到父参考系；根参考系省略 parent。帧目录内容变化必须体现为帧目录版本变化。
type ReferenceFrame struct {
	// Name 场景内稳定的命名参考系标识；同一场景内唯一，且不得使用显示名。
	Name string `json:"name"`

	// Parent 对场景声明的命名参考系的引用。
	Parent *NamedFrameRef `json:"parent,omitempty"`

	// Transform 参考系变换链上的一环，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 FrameTransform，语义保持一致。
	Transform FrameTransform `json:"transform"`
}

// RequirementSatisfactionState 任务保障要求满足度状态。使用三态枚举（SATISFIED / VIOLATED / IN_PROGRESS / UNKNOWN），防止在途任务被误判为违背。
type RequirementSatisfactionState struct {
	// DeadlineSatisfied 任务保障要求满足状态的三态枚举（SATISFIED=已满足, VIOLATED=明确违背, IN_PROGRESS=在途未决断, UNKNOWN=未声明或未采集）。避免在途任务被误标为未满足导致监督信号污染（ADR D-0015）。
	DeadlineSatisfied *SatisfactionState `json:"deadline_satisfied,omitempty"`

	// LatencySatisfied 任务保障要求满足状态的三态枚举（SATISFIED=已满足, VIOLATED=明确违背, IN_PROGRESS=在途未决断, UNKNOWN=未声明或未采集）。避免在途任务被误标为未满足导致监督信号污染（ADR D-0015）。
	LatencySatisfied *SatisfactionState `json:"latency_satisfied,omitempty"`

	// OverallSatisfied 任务保障要求满足状态的三态枚举（SATISFIED=已满足, VIOLATED=明确违背, IN_PROGRESS=在途未决断, UNKNOWN=未声明或未采集）。避免在途任务被误标为未满足导致监督信号污染（ADR D-0015）。
	OverallSatisfied *SatisfactionState `json:"overall_satisfied,omitempty"`

	// ReliabilitySatisfied 任务保障要求满足状态的三态枚举（SATISFIED=已满足, VIOLATED=明确违背, IN_PROGRESS=在途未决断, UNKNOWN=未声明或未采集）。避免在途任务被误标为未满足导致监督信号污染（ADR D-0015）。
	ReliabilitySatisfied *SatisfactionState `json:"reliability_satisfied,omitempty"`

	// ThroughputSatisfied 任务保障要求满足状态的三态枚举（SATISFIED=已满足, VIOLATED=明确违背, IN_PROGRESS=在途未决断, UNKNOWN=未声明或未采集）。避免在途任务被误标为未满足导致监督信号污染（ADR D-0015）。
	ThroughputSatisfied *SatisfactionState `json:"throughput_satisfied,omitempty"`
}

// ResourceAllocation 显式表示网络资源当前被谁占用多少，用于学习任务保障、抢占和资源倾斜规律。
type ResourceAllocation struct {
	AllocationId string `json:"allocation_id"`

	// Bandwidth 为消费者分配的带宽。
	Bandwidth *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"bandwidth,omitempty"`

	// Compute 为消费者分配的计算资源。
	Compute *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"compute,omitempty"`
	Consumer ConsumerRef `json:"consumer"`

	// Priority 该资源分配记录对应的调度优先级。
	Priority *int        `json:"priority,omitempty"`
	Resource ResourceRef `json:"resource"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`
}

// ResourceRef defines model for ResourceRef.
type ResourceRef struct {
	// ResourceId 对应资源对象 ID。
	ResourceId string `json:"resource_id"`

	// Type 被分配的资源类型。
	Type ResourceRefType `json:"type"`
}

// ResourceRefType 被分配的资源类型。
type ResourceRefType string

// SatisfactionState 任务保障要求满足状态的三态枚举（SATISFIED=已满足, VIOLATED=明确违背, IN_PROGRESS=在途未决断, UNKNOWN=未声明或未采集）。避免在途任务被误标为未满足导致监督信号污染（ADR D-0015）。
type SatisfactionState string

// ScenarioTime 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
type ScenarioTime struct {
	// Unit 场景时间统一以秒表示。
	Unit ScenarioTimeUnit `json:"unit"`

	// Value 自场景起点开始累计的时间值。
	Value float32 `json:"value"`
}

// ScenarioTimeUnit 场景时间统一以秒表示。
type ScenarioTimeUnit string

// SchemaMetadata 标识当前 Network World State 数据契约的名称和版本。
type SchemaMetadata struct {
	// Name Schema 固定名称。
	Name SchemaMetadataName `json:"name"`

	// Version Schema 版本。第一阶段建议使用语义化或显式版本号，例如 0.1。
	Version string `json:"version"`
}

// SchemaMetadataName Schema 固定名称。
type SchemaMetadataName string

// SphereBodyShape 球形天体形状。
type SphereBodyShape struct {
	// RadiusM 球半径，单位为米。
	RadiusM float64             `json:"radius_m"`
	Type    SphereBodyShapeType `json:"type"`
}

// SphereBodyShapeType defines model for SphereBodyShape.Type.
type SphereBodyShapeType string

// TargetRef defines model for TargetRef.
type TargetRef struct {
	// Id 目标对象 ID。全局对象可为空，例如 PHYSICAL_WORLD。
	Id *string `json:"id,omitempty"`

	// Type 事件或外部行为的目标对象类型。
	Type TargetRefType `json:"type"`
}

// TargetRefType 事件或外部行为的目标对象类型。
type TargetRefType string

// Task 第一阶段统一业务/任务抽象。Task 可产生 0..N Traffic Demand，并通过 requirements 表达任务保障目标。
type Task struct {
	// CanPreemptOthers 该任务是否允许抢占其他任务资源。
	CanPreemptOthers bool `json:"can_preempt_others"`

	// CompletionCriterion 任务完成的判定语义。
	CompletionCriterion TaskCompletionCriterion `json:"completion_criterion"`

	// Deadline 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	Deadline *ScenarioTime `json:"deadline,omitempty"`

	// DeliveryMode GUARANTEED=强调成功交付，BEST_EFFORT=尽力而为，FIRE_AND_FORGET=源端发出即可。
	DeliveryMode TaskDeliveryMode `json:"delivery_mode"`
	Destinations []string         `json:"destinations"`

	// EarliestStart 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	EarliestStart *ScenarioTime           `json:"earliest_start,omitempty"`
	Extensions    *map[string]interface{} `json:"extensions,omitempty"`

	// PayloadSize 任务总负载/数据规模。
	PayloadSize struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"payload_size"`

	// Preemptible 该任务自身是否允许被其他任务抢占。
	Preemptible bool `json:"preemptible"`

	// Priority 任务优先级。数值用于精细比较，class 用于语义分类。
	Priority TaskPriority `json:"priority"`

	// Requirements 任务对网络和执行过程提出的约束与优化目标。
	Requirements TaskRequirements `json:"requirements"`
	SourceNode   string           `json:"source_node"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`

	// State 任务在当前 scenario_time 下的执行状态。
	State TaskState `json:"state"`

	// SubmittedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	SubmittedAt ScenarioTime `json:"submitted_at"`
	TaskId      string       `json:"task_id"`

	// TaskType 任务类型，由业务系统定义。
	TaskType string `json:"task_type"`
}

// TaskCompletionCriterion 任务完成的判定语义。
type TaskCompletionCriterion string

// TaskDeliveryMode GUARANTEED=强调成功交付，BEST_EFFORT=尽力而为，FIRE_AND_FORGET=源端发出即可。
type TaskDeliveryMode string

// TaskDerivedMetrics defines model for TaskDerivedMetrics.
type TaskDerivedMetrics struct {
	CompletedTasks                *int     `json:"completed_tasks,omitempty"`
	DeadlineViolationCount        *int     `json:"deadline_violation_count,omitempty"`
	FailedTasks                   *int     `json:"failed_tasks,omitempty"`
	HighPrioritySatisfactionRatio *float32 `json:"high_priority_satisfaction_ratio,omitempty"`
	RunningTasks                  *int     `json:"running_tasks,omitempty"`
	TotalTasks                    *int     `json:"total_tasks,omitempty"`
}

// TaskPriority 任务优先级。数值用于精细比较，class 用于语义分类。
type TaskPriority struct {
	// Class 语义优先级。
	Class TaskPriorityClass `json:"class"`

	// Value 优先级数值，值越大表示优先级越高。
	Value int `json:"value"`
}

// TaskPriorityClass 语义优先级。
type TaskPriorityClass string

// TaskRequirements 任务对网络和执行过程提出的约束与优化目标。
type TaskRequirements struct {
	Completion struct {
		// DeadlineRequired 是否要求在 deadline 前完成。
		DeadlineRequired bool `json:"deadline_required"`

		// MustComplete 任务是否要求最终完成。
		MustComplete bool `json:"must_complete"`
	} `json:"completion"`
	Latency struct {
		// ConstraintType 时延要求约束类型。
		ConstraintType TaskRequirementsLatencyConstraintType `json:"constraint_type"`
		Enabled        bool                                  `json:"enabled"`

		// Max 任务允许的最大时延。
		Max *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"max,omitempty"`
	} `json:"latency"`
	Reliability struct {
		// ConstraintType 可靠性约束类型。
		ConstraintType TaskRequirementsReliabilityConstraintType `json:"constraint_type"`
		Enabled        bool                                      `json:"enabled"`

		// MinimumDeliveryProbability 最低成功交付概率。
		MinimumDeliveryProbability *float32 `json:"minimum_delivery_probability,omitempty"`
	} `json:"reliability"`
	Throughput struct {
		Enabled bool `json:"enabled"`

		// Minimum 最低吞吐要求。
		Minimum *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"minimum,omitempty"`

		// Preferred 偏好的目标吞吐。
		Preferred *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"preferred,omitempty"`
	} `json:"throughput"`
}

// TaskRequirementsLatencyConstraintType 时延要求约束类型。
type TaskRequirementsLatencyConstraintType string

// TaskRequirementsReliabilityConstraintType 可靠性约束类型。
type TaskRequirementsReliabilityConstraintType string

// TaskState 任务在当前 scenario_time 下的执行状态。
type TaskState struct {
	// BytesDelivered 目的端已成功交付数据量。
	BytesDelivered struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_delivered"`

	// BytesSent 源端已发送数据量。
	BytesSent struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_sent"`

	// BytesTotal 任务总数据量。
	BytesTotal struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_total"`

	// CompletedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	CompletedAt *ScenarioTime `json:"completed_at,omitempty"`

	// EstimatedCompletionTime 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	EstimatedCompletionTime *ScenarioTime `json:"estimated_completion_time,omitempty"`

	// Progress 任务完成进度 0~1。
	Progress float32 `json:"progress"`

	// RequirementSatisfaction 任务保障要求满足度状态。使用三态枚举（SATISFIED / VIOLATED / IN_PROGRESS / UNKNOWN），防止在途任务被误判为违背。
	RequirementSatisfaction *RequirementSatisfactionState `json:"requirement_satisfaction,omitempty"`

	// StartedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	StartedAt *ScenarioTime `json:"started_at,omitempty"`

	// Status 任务生命周期状态。
	Status TaskStateStatus `json:"status"`
}

// TaskStateStatus 任务生命周期状态。
type TaskStateStatus string

// TimeBase 把世界模型的内部时间轴（scenario_time，相对秒）锚定到外部系统的绝对时刻。该绑定在一个场景内唯一且不变，否则 ObservationStamp 中的 Instant 无法与scenario_time 互相换算。缺少该绑定的快照不能声称自己能独立解释观测时刻。
type TimeBase struct {
	// ScenarioEpoch 绝对时刻 + 时间尺度，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Instant，语义保持一致。 value 是不带时区后缀的扩展 ISO-8601，scale 单独决定时间尺度。 世界模型自身的内部时间轴仍是 scenario_time；Instant 只用于把观测锚定到外部系统的绝对时间，二者通过 TimeBase 换算。
	ScenarioEpoch Instant `json:"scenario_epoch"`

	// SimulationStart 绝对时刻 + 时间尺度，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Instant，语义保持一致。 value 是不带时区后缀的扩展 ISO-8601，scale 单独决定时间尺度。 世界模型自身的内部时间轴仍是 scenario_time；Instant 只用于把观测锚定到外部系统的绝对时间，二者通过 TimeBase 换算。
	SimulationStart Instant `json:"simulation_start"`

	// TickS 逻辑仿真 tick 长度，单位为秒。用于表达观测的最细时间粒度，也是时序对齐 binning 窗口的下界。
	TickS *float32 `json:"tick_s,omitempty"`
}

// TrafficAggregateState defines model for TrafficAggregateState.
type TrafficAggregateState struct {
	// CongestedLinks 被判定为拥塞的 link_id 列表。
	CongestedLinks []string `json:"congested_links"`

	// TotalDeliveredTraffic 全网总 delivered traffic。
	TotalDeliveredTraffic struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"total_delivered_traffic"`

	// TotalOfferedTraffic 全网总 offered traffic。
	TotalOfferedTraffic struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"total_offered_traffic"`
}

// TrafficDemand 尚未等价于实际 Flow 的网络通信需求：描述谁想向谁发送多少数据或多大速率。
type TrafficDemand struct {
	DemandId        string `json:"demand_id"`
	DestinationNode string `json:"destination_node"`

	// GeneratedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	GeneratedAt ScenarioTime `json:"generated_at"`

	// RequestedRate 期望速率。
	RequestedRate *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"requested_rate,omitempty"`
	SourceNode string `json:"source_node"`

	// Stamp 一次观测的溯源与有效窗口，是异步/部分观测对齐的基础。observed_at_instant 与 observed_at_scenario_time 至少提供一个：前者是源系统报告的绝对时刻，后者是已对齐到世界模型时间轴的时刻（该条约束由跨字段校验执行）。valid_from/valid_until 是半开区间 [valid_from, valid_until)，省略 valid_until 表示开区间。重新观测到一个未变化的值不构成状态变化。
	Stamp *ObservationStamp `json:"stamp,omitempty"`

	// TaskId 产生该需求的 Task，可为空。
	TaskId *string `json:"task_id,omitempty"`

	// TotalDataSize 待传输数据总量。
	TotalDataSize *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"total_data_size,omitempty"`
}

// TrafficResource defines model for TrafficResource.
type TrafficResource struct {
	AggregateState *TrafficAggregateState `json:"aggregate_state,omitempty"`
	Allocations    []ResourceAllocation   `json:"allocations"`
	Demands        []TrafficDemand        `json:"demands"`
	Flows          []Flow                 `json:"flows"`
}

// UniformRotationFrameTransform 匀速旋转变换：子参考系相对父参考系绕固定轴匀速旋转。
type UniformRotationFrameTransform struct {
	// AxisParent 三维向量 [x, y, z]，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Vec3，语义保持一致。 单位由引用它的字段名声明显式声明（例如 _m、_m_s、_rad_s），不得依赖调用方推测。
	AxisParent Vec3 `json:"axis_parent"`

	// Epoch 绝对时刻 + 时间尺度，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Instant，语义保持一致。 value 是不带时区后缀的扩展 ISO-8601，scale 单独决定时间尺度。 世界模型自身的内部时间轴仍是 scenario_time；Instant 只用于把观测锚定到外部系统的绝对时间，二者通过 TimeBase 换算。
	Epoch Instant `json:"epoch"`

	// OriginParentM 三维向量 [x, y, z]，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Vec3，语义保持一致。 单位由引用它的字段名声明显式声明（例如 _m、_m_s、_rad_s），不得依赖调用方推测。
	OriginParentM Vec3 `json:"origin_parent_m"`

	// PhaseAtEpochRad 历元时绕旋转轴的相位，单位为 rad。
	PhaseAtEpochRad float64 `json:"phase_at_epoch_rad"`

	// RateRadS 角速度，单位为 rad/s。
	RateRadS float64                           `json:"rate_rad_s"`
	Type     UniformRotationFrameTransformType `json:"type"`
}

// UniformRotationFrameTransformType defines model for UniformRotationFrameTransform.Type.
type UniformRotationFrameTransformType string

// Vec3 三维向量 [x, y, z]，vendored from astra-emu-api Config 契约（来源见 contracts/vendoring.yaml） 的 Vec3，语义保持一致。 单位由引用它的字段名声明显式声明（例如 _m、_m_s、_rad_s），不得依赖调用方推测。
type Vec3 = []float64

// Velocity 节点在当前 scenario_time 下相对于 position.frame 的速度。
type Velocity struct {
	// Vx X 轴速度。
	Vx struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"vx"`

	// Vy Y 轴速度。
	Vy struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"vy"`

	// Vz Z 轴速度。
	Vz struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"vz"`
}

// WorldEvent 发生在世界中的外部事件，例如自然故障、干扰或环境变化。
type WorldEvent struct {
	// Duration 事件持续时间。
	Duration *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"duration,omitempty"`
	EventId string `json:"event_id"`

	// EventType 事件类型。
	EventType WorldEventEventType `json:"event_type"`

	// OccurredAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	OccurredAt ScenarioTime `json:"occurred_at"`

	// Parameters 事件特有参数，例如故障程度、干扰功率、环境变化量。
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Target     TargetRef               `json:"target"`
}

// WorldEventEventType 事件类型。
type WorldEventEventType string

// WorldState 网络与物理世界的动态状态本体容器，与外部信封元数据解耦。
type WorldState struct {
	// Network 内生通信网络完整拓扑、资源、业务、事件与动作的高频运行状态。
	Network NetworkState `json:"network"`

	// PhysicalWorld 节点之外客观存在的物理环境。用于描述空间、地理、大气、电磁、干扰及传播环境。节点的位置、速度、姿态等属于 Node State。
	PhysicalWorld *PhysicalWorld `json:"physical_world,omitempty"`
}

// Getter for additional properties for Constraint. Returns the specified
// element and whether it was found
func (a Constraint) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Constraint
func (a *Constraint) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Constraint to handle AdditionalProperties
func (a *Constraint) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["constraint_type"]; found {
		err = json.Unmarshal(raw, &a.ConstraintType)
		if err != nil {
			return fmt.Errorf("error reading 'constraint_type': %w", err)
		}
		delete(object, "constraint_type")
	}

	if raw, found := object["enabled"]; found {
		err = json.Unmarshal(raw, &a.Enabled)
		if err != nil {
			return fmt.Errorf("error reading 'enabled': %w", err)
		}
		delete(object, "enabled")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Constraint to handle AdditionalProperties
func (a Constraint) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["constraint_type"], err = json.Marshal(a.ConstraintType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'constraint_type': %w", err)
	}

	object["enabled"], err = json.Marshal(a.Enabled)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'enabled': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsSphereBodyShape returns the union data inside the BodyShape as a SphereBodyShape
func (t BodyShape) AsSphereBodyShape() (SphereBodyShape, error) {
	var body SphereBodyShape
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSphereBodyShape overwrites any union data inside the BodyShape as the provided SphereBodyShape
func (t *BodyShape) FromSphereBodyShape(v SphereBodyShape) error {
	v.Type = "Sphere"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSphereBodyShape performs a merge with any union data inside the BodyShape, using the provided SphereBodyShape
func (t *BodyShape) MergeSphereBodyShape(v SphereBodyShape) error {
	v.Type = "Sphere"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOblateEllipsoidBodyShape returns the union data inside the BodyShape as a OblateEllipsoidBodyShape
func (t BodyShape) AsOblateEllipsoidBodyShape() (OblateEllipsoidBodyShape, error) {
	var body OblateEllipsoidBodyShape
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOblateEllipsoidBodyShape overwrites any union data inside the BodyShape as the provided OblateEllipsoidBodyShape
func (t *BodyShape) FromOblateEllipsoidBodyShape(v OblateEllipsoidBodyShape) error {
	v.Type = "OblateEllipsoid"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOblateEllipsoidBodyShape performs a merge with any union data inside the BodyShape, using the provided OblateEllipsoidBodyShape
func (t *BodyShape) MergeOblateEllipsoidBodyShape(v OblateEllipsoidBodyShape) error {
	v.Type = "OblateEllipsoid"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BodyShape) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t BodyShape) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "OblateEllipsoid":
		return t.AsOblateEllipsoidBodyShape()
	case "Sphere":
		return t.AsSphereBodyShape()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t BodyShape) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *BodyShape) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNamedFrameRef returns the union data inside the FrameRef as a NamedFrameRef
func (t FrameRef) AsNamedFrameRef() (NamedFrameRef, error) {
	var body NamedFrameRef
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNamedFrameRef overwrites any union data inside the FrameRef as the provided NamedFrameRef
func (t *FrameRef) FromNamedFrameRef(v NamedFrameRef) error {
	v.Type = "NamedFrame"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNamedFrameRef performs a merge with any union data inside the FrameRef, using the provided NamedFrameRef
func (t *FrameRef) MergeNamedFrameRef(v NamedFrameRef) error {
	v.Type = "NamedFrame"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNodeBodyFrameRef returns the union data inside the FrameRef as a NodeBodyFrameRef
func (t FrameRef) AsNodeBodyFrameRef() (NodeBodyFrameRef, error) {
	var body NodeBodyFrameRef
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNodeBodyFrameRef overwrites any union data inside the FrameRef as the provided NodeBodyFrameRef
func (t *FrameRef) FromNodeBodyFrameRef(v NodeBodyFrameRef) error {
	v.Type = "NodeBodyFrame"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNodeBodyFrameRef performs a merge with any union data inside the FrameRef, using the provided NodeBodyFrameRef
func (t *FrameRef) MergeNodeBodyFrameRef(v NodeBodyFrameRef) error {
	v.Type = "NodeBodyFrame"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FrameRef) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t FrameRef) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "NamedFrame":
		return t.AsNamedFrameRef()
	case "NodeBodyFrame":
		return t.AsNodeBodyFrameRef()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t FrameRef) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FrameRef) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsIdentityFrameTransform returns the union data inside the FrameTransform as a IdentityFrameTransform
func (t FrameTransform) AsIdentityFrameTransform() (IdentityFrameTransform, error) {
	var body IdentityFrameTransform
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIdentityFrameTransform overwrites any union data inside the FrameTransform as the provided IdentityFrameTransform
func (t *FrameTransform) FromIdentityFrameTransform(v IdentityFrameTransform) error {
	v.Type = "Identity"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIdentityFrameTransform performs a merge with any union data inside the FrameTransform, using the provided IdentityFrameTransform
func (t *FrameTransform) MergeIdentityFrameTransform(v IdentityFrameTransform) error {
	v.Type = "Identity"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFixedFrameTransform returns the union data inside the FrameTransform as a FixedFrameTransform
func (t FrameTransform) AsFixedFrameTransform() (FixedFrameTransform, error) {
	var body FixedFrameTransform
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFixedFrameTransform overwrites any union data inside the FrameTransform as the provided FixedFrameTransform
func (t *FrameTransform) FromFixedFrameTransform(v FixedFrameTransform) error {
	v.Type = "Fixed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFixedFrameTransform performs a merge with any union data inside the FrameTransform, using the provided FixedFrameTransform
func (t *FrameTransform) MergeFixedFrameTransform(v FixedFrameTransform) error {
	v.Type = "Fixed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUniformRotationFrameTransform returns the union data inside the FrameTransform as a UniformRotationFrameTransform
func (t FrameTransform) AsUniformRotationFrameTransform() (UniformRotationFrameTransform, error) {
	var body UniformRotationFrameTransform
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUniformRotationFrameTransform overwrites any union data inside the FrameTransform as the provided UniformRotationFrameTransform
func (t *FrameTransform) FromUniformRotationFrameTransform(v UniformRotationFrameTransform) error {
	v.Type = "UniformRotation"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUniformRotationFrameTransform performs a merge with any union data inside the FrameTransform, using the provided UniformRotationFrameTransform
func (t *FrameTransform) MergeUniformRotationFrameTransform(v UniformRotationFrameTransform) error {
	v.Type = "UniformRotation"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEphemerisFrameTransform returns the union data inside the FrameTransform as a EphemerisFrameTransform
func (t FrameTransform) AsEphemerisFrameTransform() (EphemerisFrameTransform, error) {
	var body EphemerisFrameTransform
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEphemerisFrameTransform overwrites any union data inside the FrameTransform as the provided EphemerisFrameTransform
func (t *FrameTransform) FromEphemerisFrameTransform(v EphemerisFrameTransform) error {
	v.Type = "Ephemeris"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEphemerisFrameTransform performs a merge with any union data inside the FrameTransform, using the provided EphemerisFrameTransform
func (t *FrameTransform) MergeEphemerisFrameTransform(v EphemerisFrameTransform) error {
	v.Type = "Ephemeris"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FrameTransform) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t FrameTransform) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Ephemeris":
		return t.AsEphemerisFrameTransform()
	case "Fixed":
		return t.AsFixedFrameTransform()
	case "Identity":
		return t.AsIdentityFrameTransform()
	case "UniformRotation":
		return t.AsUniformRotationFrameTransform()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t FrameTransform) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FrameTransform) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCartesianObservationFormat returns the union data inside the ObservationPositionFormat as a CartesianObservationFormat
func (t ObservationPositionFormat) AsCartesianObservationFormat() (CartesianObservationFormat, error) {
	var body CartesianObservationFormat
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCartesianObservationFormat overwrites any union data inside the ObservationPositionFormat as the provided CartesianObservationFormat
func (t *ObservationPositionFormat) FromCartesianObservationFormat(v CartesianObservationFormat) error {
	v.Type = "Cartesian"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCartesianObservationFormat performs a merge with any union data inside the ObservationPositionFormat, using the provided CartesianObservationFormat
func (t *ObservationPositionFormat) MergeCartesianObservationFormat(v CartesianObservationFormat) error {
	v.Type = "Cartesian"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGeodeticObservationFormat returns the union data inside the ObservationPositionFormat as a GeodeticObservationFormat
func (t ObservationPositionFormat) AsGeodeticObservationFormat() (GeodeticObservationFormat, error) {
	var body GeodeticObservationFormat
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeodeticObservationFormat overwrites any union data inside the ObservationPositionFormat as the provided GeodeticObservationFormat
func (t *ObservationPositionFormat) FromGeodeticObservationFormat(v GeodeticObservationFormat) error {
	v.Type = "Geodetic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeodeticObservationFormat performs a merge with any union data inside the ObservationPositionFormat, using the provided GeodeticObservationFormat
func (t *ObservationPositionFormat) MergeGeodeticObservationFormat(v GeodeticObservationFormat) error {
	v.Type = "Geodetic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ObservationPositionFormat) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ObservationPositionFormat) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Cartesian":
		return t.AsCartesianObservationFormat()
	case "Geodetic":
		return t.AsGeodeticObservationFormat()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ObservationPositionFormat) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ObservationPositionFormat) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
