// Package worldstate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package worldstate

import (
	"encoding/json"
	"fmt"
)

// Defines values for CommunicationTerminalCapabilityDuplex.
const (
	CommunicationTerminalCapabilityDuplexFULL    CommunicationTerminalCapabilityDuplex = "FULL"
	CommunicationTerminalCapabilityDuplexHALF    CommunicationTerminalCapabilityDuplex = "HALF"
	CommunicationTerminalCapabilityDuplexUNKNOWN CommunicationTerminalCapabilityDuplex = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the CommunicationTerminalCapabilityDuplex enum.
func (e CommunicationTerminalCapabilityDuplex) Valid() bool {
	switch e {
	case CommunicationTerminalCapabilityDuplexFULL:
		return true
	case CommunicationTerminalCapabilityDuplexHALF:
		return true
	case CommunicationTerminalCapabilityDuplexUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for CommunicationTerminalCapabilityTerminalType.
const (
	CommunicationTerminalCapabilityTerminalTypeETHERNET  CommunicationTerminalCapabilityTerminalType = "ETHERNET"
	CommunicationTerminalCapabilityTerminalTypeGENERIC   CommunicationTerminalCapabilityTerminalType = "GENERIC"
	CommunicationTerminalCapabilityTerminalTypeLASER     CommunicationTerminalCapabilityTerminalType = "LASER"
	CommunicationTerminalCapabilityTerminalTypeMICROWAVE CommunicationTerminalCapabilityTerminalType = "MICROWAVE"
	CommunicationTerminalCapabilityTerminalTypeOPTICAL   CommunicationTerminalCapabilityTerminalType = "OPTICAL"
	CommunicationTerminalCapabilityTerminalTypeRADIO     CommunicationTerminalCapabilityTerminalType = "RADIO"
	CommunicationTerminalCapabilityTerminalTypeRF        CommunicationTerminalCapabilityTerminalType = "RF"
)

// Valid indicates whether the value is a known member of the CommunicationTerminalCapabilityTerminalType enum.
func (e CommunicationTerminalCapabilityTerminalType) Valid() bool {
	switch e {
	case CommunicationTerminalCapabilityTerminalTypeETHERNET:
		return true
	case CommunicationTerminalCapabilityTerminalTypeGENERIC:
		return true
	case CommunicationTerminalCapabilityTerminalTypeLASER:
		return true
	case CommunicationTerminalCapabilityTerminalTypeMICROWAVE:
		return true
	case CommunicationTerminalCapabilityTerminalTypeOPTICAL:
		return true
	case CommunicationTerminalCapabilityTerminalTypeRADIO:
		return true
	case CommunicationTerminalCapabilityTerminalTypeRF:
		return true
	default:
		return false
	}
}

// Defines values for ConstraintConstraintType.
const (
	ConstraintConstraintTypeHARD      ConstraintConstraintType = "HARD"
	ConstraintConstraintTypeOBJECTIVE ConstraintConstraintType = "OBJECTIVE"
	ConstraintConstraintTypeSOFT      ConstraintConstraintType = "SOFT"
)

// Valid indicates whether the value is a known member of the ConstraintConstraintType enum.
func (e ConstraintConstraintType) Valid() bool {
	switch e {
	case ConstraintConstraintTypeHARD:
		return true
	case ConstraintConstraintTypeOBJECTIVE:
		return true
	case ConstraintConstraintTypeSOFT:
		return true
	default:
		return false
	}
}

// Defines values for ConsumerRefType.
const (
	ConsumerRefTypeFLOW ConsumerRefType = "FLOW"
	ConsumerRefTypeTASK ConsumerRefType = "TASK"
)

// Valid indicates whether the value is a known member of the ConsumerRefType enum.
func (e ConsumerRefType) Valid() bool {
	switch e {
	case ConsumerRefTypeFLOW:
		return true
	case ConsumerRefTypeTASK:
		return true
	default:
		return false
	}
}

// Defines values for DestinationType.
const (
	ADDRESS DestinationType = "ADDRESS"
	NODE    DestinationType = "NODE"
	PREFIX  DestinationType = "PREFIX"
)

// Valid indicates whether the value is a known member of the DestinationType enum.
func (e DestinationType) Valid() bool {
	switch e {
	case ADDRESS:
		return true
	case NODE:
		return true
	case PREFIX:
		return true
	default:
		return false
	}
}

// Defines values for ExternalActionActionType.
const (
	ExternalActionActionTypeENVIRONMENTCHANGE ExternalActionActionType = "ENVIRONMENT_CHANGE"
	ExternalActionActionTypeINTENTCHANGE      ExternalActionActionType = "INTENT_CHANGE"
	ExternalActionActionTypeLINKFORCEDOWN     ExternalActionActionType = "LINK_FORCE_DOWN"
	ExternalActionActionTypeLINKFORCEUP       ExternalActionActionType = "LINK_FORCE_UP"
	ExternalActionActionTypeNODEFORCEDISABLE  ExternalActionActionType = "NODE_FORCE_DISABLE"
	ExternalActionActionTypeNODEFORCEENABLE   ExternalActionActionType = "NODE_FORCE_ENABLE"
	ExternalActionActionTypeTASKCANCEL        ExternalActionActionType = "TASK_CANCEL"
	ExternalActionActionTypeTASKMODIFY        ExternalActionActionType = "TASK_MODIFY"
	ExternalActionActionTypeTASKSUBMIT        ExternalActionActionType = "TASK_SUBMIT"
)

// Valid indicates whether the value is a known member of the ExternalActionActionType enum.
func (e ExternalActionActionType) Valid() bool {
	switch e {
	case ExternalActionActionTypeENVIRONMENTCHANGE:
		return true
	case ExternalActionActionTypeINTENTCHANGE:
		return true
	case ExternalActionActionTypeLINKFORCEDOWN:
		return true
	case ExternalActionActionTypeLINKFORCEUP:
		return true
	case ExternalActionActionTypeNODEFORCEDISABLE:
		return true
	case ExternalActionActionTypeNODEFORCEENABLE:
		return true
	case ExternalActionActionTypeTASKCANCEL:
		return true
	case ExternalActionActionTypeTASKMODIFY:
		return true
	case ExternalActionActionTypeTASKSUBMIT:
		return true
	default:
		return false
	}
}

// Defines values for FlowTransportType.
const (
	FlowTransportTypeGENERIC FlowTransportType = "GENERIC"
	FlowTransportTypeRAW     FlowTransportType = "RAW"
	FlowTransportTypeTCP     FlowTransportType = "TCP"
	FlowTransportTypeUDP     FlowTransportType = "UDP"
)

// Valid indicates whether the value is a known member of the FlowTransportType enum.
func (e FlowTransportType) Valid() bool {
	switch e {
	case FlowTransportTypeGENERIC:
		return true
	case FlowTransportTypeRAW:
		return true
	case FlowTransportTypeTCP:
		return true
	case FlowTransportTypeUDP:
		return true
	default:
		return false
	}
}

// Defines values for FlowStateStatus.
const (
	FlowStateStatusACTIVE    FlowStateStatus = "ACTIVE"
	FlowStateStatusCOMPLETED FlowStateStatus = "COMPLETED"
	FlowStateStatusFAILED    FlowStateStatus = "FAILED"
	FlowStateStatusPAUSED    FlowStateStatus = "PAUSED"
	FlowStateStatusQUEUED    FlowStateStatus = "QUEUED"
)

// Valid indicates whether the value is a known member of the FlowStateStatus enum.
func (e FlowStateStatus) Valid() bool {
	switch e {
	case FlowStateStatusACTIVE:
		return true
	case FlowStateStatusCOMPLETED:
		return true
	case FlowStateStatusFAILED:
		return true
	case FlowStateStatusPAUSED:
		return true
	case FlowStateStatusQUEUED:
		return true
	default:
		return false
	}
}

// Defines values for IPAddressFamily.
const (
	IPV4 IPAddressFamily = "IPV4"
	IPV6 IPAddressFamily = "IPV6"
)

// Valid indicates whether the value is a known member of the IPAddressFamily enum.
func (e IPAddressFamily) Valid() bool {
	switch e {
	case IPV4:
		return true
	case IPV6:
		return true
	default:
		return false
	}
}

// Defines values for L2LinkLinkClass.
const (
	L2LinkLinkClassAIRAIR      L2LinkLinkClass = "AIR_AIR"
	L2LinkLinkClassAIRGROUND   L2LinkLinkClass = "AIR_GROUND"
	L2LinkLinkClassGENERIC     L2LinkLinkClass = "GENERIC"
	L2LinkLinkClassISL         L2LinkLinkClass = "ISL"
	L2LinkLinkClassSEAGROUND   L2LinkLinkClass = "SEA_GROUND"
	L2LinkLinkClassSPACEGROUND L2LinkLinkClass = "SPACE_GROUND"
	L2LinkLinkClassTERRESTRIAL L2LinkLinkClass = "TERRESTRIAL"
)

// Valid indicates whether the value is a known member of the L2LinkLinkClass enum.
func (e L2LinkLinkClass) Valid() bool {
	switch e {
	case L2LinkLinkClassAIRAIR:
		return true
	case L2LinkLinkClassAIRGROUND:
		return true
	case L2LinkLinkClassGENERIC:
		return true
	case L2LinkLinkClassISL:
		return true
	case L2LinkLinkClassSEAGROUND:
		return true
	case L2LinkLinkClassSPACEGROUND:
		return true
	case L2LinkLinkClassTERRESTRIAL:
		return true
	default:
		return false
	}
}

// Defines values for L2LinkMedium.
const (
	L2LinkMediumETHERNET  L2LinkMedium = "ETHERNET"
	L2LinkMediumFIBER     L2LinkMedium = "FIBER"
	L2LinkMediumGENERIC   L2LinkMedium = "GENERIC"
	L2LinkMediumLASER     L2LinkMedium = "LASER"
	L2LinkMediumMICROWAVE L2LinkMedium = "MICROWAVE"
	L2LinkMediumOPTICAL   L2LinkMedium = "OPTICAL"
	L2LinkMediumRF        L2LinkMedium = "RF"
)

// Valid indicates whether the value is a known member of the L2LinkMedium enum.
func (e L2LinkMedium) Valid() bool {
	switch e {
	case L2LinkMediumETHERNET:
		return true
	case L2LinkMediumFIBER:
		return true
	case L2LinkMediumGENERIC:
		return true
	case L2LinkMediumLASER:
		return true
	case L2LinkMediumMICROWAVE:
		return true
	case L2LinkMediumOPTICAL:
		return true
	case L2LinkMediumRF:
		return true
	default:
		return false
	}
}

// Defines values for L2LinkStatus.
const (
	L2LinkStatusDEGRADED L2LinkStatus = "DEGRADED"
	L2LinkStatusDOWN     L2LinkStatus = "DOWN"
	L2LinkStatusUNKNOWN  L2LinkStatus = "UNKNOWN"
	L2LinkStatusUP       L2LinkStatus = "UP"
)

// Valid indicates whether the value is a known member of the L2LinkStatus enum.
func (e L2LinkStatus) Valid() bool {
	switch e {
	case L2LinkStatusDEGRADED:
		return true
	case L2LinkStatusDOWN:
		return true
	case L2LinkStatusUNKNOWN:
		return true
	case L2LinkStatusUP:
		return true
	default:
		return false
	}
}

// Defines values for L3LogicalLinkType.
const (
	L3LogicalLinkTypeDIRECT  L3LogicalLinkType = "DIRECT"
	L3LogicalLinkTypeGENERIC L3LogicalLinkType = "GENERIC"
	L3LogicalLinkTypeOVERLAY L3LogicalLinkType = "OVERLAY"
	L3LogicalLinkTypeTUNNEL  L3LogicalLinkType = "TUNNEL"
)

// Valid indicates whether the value is a known member of the L3LogicalLinkType enum.
func (e L3LogicalLinkType) Valid() bool {
	switch e {
	case L3LogicalLinkTypeDIRECT:
		return true
	case L3LogicalLinkTypeGENERIC:
		return true
	case L3LogicalLinkTypeOVERLAY:
		return true
	case L3LogicalLinkTypeTUNNEL:
		return true
	default:
		return false
	}
}

// Defines values for L3PathDerived.
const (
	L3PathDerivedTrue L3PathDerived = true
)

// Valid indicates whether the value is a known member of the L3PathDerived enum.
func (e L3PathDerived) Valid() bool {
	switch e {
	case L3PathDerivedTrue:
		return true
	default:
		return false
	}
}

// Defines values for NodeNodeType.
const (
	NodeNodeTypeAIRCRAFT      NodeNodeType = "AIRCRAFT"
	NodeNodeTypeGENERIC       NodeNodeType = "GENERIC"
	NodeNodeTypeGROUNDSTATION NodeNodeType = "GROUND_STATION"
	NodeNodeTypeROUTER        NodeNodeType = "ROUTER"
	NodeNodeTypeSATELLITE     NodeNodeType = "SATELLITE"
	NodeNodeTypeSERVER        NodeNodeType = "SERVER"
	NodeNodeTypeSHIP          NodeNodeType = "SHIP"
	NodeNodeTypeSWITCH        NodeNodeType = "SWITCH"
	NodeNodeTypeTERMINAL      NodeNodeType = "TERMINAL"
	NodeNodeTypeUAV           NodeNodeType = "UAV"
	NodeNodeTypeVEHICLE       NodeNodeType = "VEHICLE"
)

// Valid indicates whether the value is a known member of the NodeNodeType enum.
func (e NodeNodeType) Valid() bool {
	switch e {
	case NodeNodeTypeAIRCRAFT:
		return true
	case NodeNodeTypeGENERIC:
		return true
	case NodeNodeTypeGROUNDSTATION:
		return true
	case NodeNodeTypeROUTER:
		return true
	case NodeNodeTypeSATELLITE:
		return true
	case NodeNodeTypeSERVER:
		return true
	case NodeNodeTypeSHIP:
		return true
	case NodeNodeTypeSWITCH:
		return true
	case NodeNodeTypeTERMINAL:
		return true
	case NodeNodeTypeUAV:
		return true
	case NodeNodeTypeVEHICLE:
		return true
	default:
		return false
	}
}

// Defines values for PhysicalWorldEnvironmentType.
const (
	PhysicalWorldEnvironmentTypeAIR         PhysicalWorldEnvironmentType = "AIR"
	PhysicalWorldEnvironmentTypeGENERIC     PhysicalWorldEnvironmentType = "GENERIC"
	PhysicalWorldEnvironmentTypeMIXED       PhysicalWorldEnvironmentType = "MIXED"
	PhysicalWorldEnvironmentTypeSEA         PhysicalWorldEnvironmentType = "SEA"
	PhysicalWorldEnvironmentTypeSPACE       PhysicalWorldEnvironmentType = "SPACE"
	PhysicalWorldEnvironmentTypeTERRESTRIAL PhysicalWorldEnvironmentType = "TERRESTRIAL"
)

// Valid indicates whether the value is a known member of the PhysicalWorldEnvironmentType enum.
func (e PhysicalWorldEnvironmentType) Valid() bool {
	switch e {
	case PhysicalWorldEnvironmentTypeAIR:
		return true
	case PhysicalWorldEnvironmentTypeGENERIC:
		return true
	case PhysicalWorldEnvironmentTypeMIXED:
		return true
	case PhysicalWorldEnvironmentTypeSEA:
		return true
	case PhysicalWorldEnvironmentTypeSPACE:
		return true
	case PhysicalWorldEnvironmentTypeTERRESTRIAL:
		return true
	default:
		return false
	}
}

// Defines values for ReachabilityEntryDerived.
const (
	ReachabilityEntryDerivedTrue ReachabilityEntryDerived = true
)

// Valid indicates whether the value is a known member of the ReachabilityEntryDerived enum.
func (e ReachabilityEntryDerived) Valid() bool {
	switch e {
	case ReachabilityEntryDerivedTrue:
		return true
	default:
		return false
	}
}

// Defines values for ResourceRefType.
const (
	ResourceRefTypeGENERIC     ResourceRefType = "GENERIC"
	ResourceRefTypeLINK        ResourceRefType = "LINK"
	ResourceRefTypeNODECOMPUTE ResourceRefType = "NODE_COMPUTE"
	ResourceRefTypeNODESTORAGE ResourceRefType = "NODE_STORAGE"
	ResourceRefTypeTERMINAL    ResourceRefType = "TERMINAL"
)

// Valid indicates whether the value is a known member of the ResourceRefType enum.
func (e ResourceRefType) Valid() bool {
	switch e {
	case ResourceRefTypeGENERIC:
		return true
	case ResourceRefTypeLINK:
		return true
	case ResourceRefTypeNODECOMPUTE:
		return true
	case ResourceRefTypeNODESTORAGE:
		return true
	case ResourceRefTypeTERMINAL:
		return true
	default:
		return false
	}
}

// Defines values for ScenarioTimeUnit.
const (
	S ScenarioTimeUnit = "s"
)

// Valid indicates whether the value is a known member of the ScenarioTimeUnit enum.
func (e ScenarioTimeUnit) Valid() bool {
	switch e {
	case S:
		return true
	default:
		return false
	}
}

// Defines values for SchemaMetadataName.
const (
	SchemaMetadataNameNetworkWorldState SchemaMetadataName = "network-world-state"
)

// Valid indicates whether the value is a known member of the SchemaMetadataName enum.
func (e SchemaMetadataName) Valid() bool {
	switch e {
	case SchemaMetadataNameNetworkWorldState:
		return true
	default:
		return false
	}
}

// Defines values for TargetRefType.
const (
	TargetRefTypeGENERIC       TargetRefType = "GENERIC"
	TargetRefTypeINTENT        TargetRefType = "INTENT"
	TargetRefTypeLINK          TargetRefType = "LINK"
	TargetRefTypeNODE          TargetRefType = "NODE"
	TargetRefTypePHYSICALWORLD TargetRefType = "PHYSICAL_WORLD"
	TargetRefTypeTASK          TargetRefType = "TASK"
	TargetRefTypeTERMINAL      TargetRefType = "TERMINAL"
)

// Valid indicates whether the value is a known member of the TargetRefType enum.
func (e TargetRefType) Valid() bool {
	switch e {
	case TargetRefTypeGENERIC:
		return true
	case TargetRefTypeINTENT:
		return true
	case TargetRefTypeLINK:
		return true
	case TargetRefTypeNODE:
		return true
	case TargetRefTypePHYSICALWORLD:
		return true
	case TargetRefTypeTASK:
		return true
	case TargetRefTypeTERMINAL:
		return true
	default:
		return false
	}
}

// Defines values for TaskCompletionCriterion.
const (
	DESTINATIONACKNOWLEDGED TaskCompletionCriterion = "DESTINATION_ACKNOWLEDGED"
	DESTINATIONRECEIVED     TaskCompletionCriterion = "DESTINATION_RECEIVED"
	SOURCESENT              TaskCompletionCriterion = "SOURCE_SENT"
)

// Valid indicates whether the value is a known member of the TaskCompletionCriterion enum.
func (e TaskCompletionCriterion) Valid() bool {
	switch e {
	case DESTINATIONACKNOWLEDGED:
		return true
	case DESTINATIONRECEIVED:
		return true
	case SOURCESENT:
		return true
	default:
		return false
	}
}

// Defines values for TaskDeliveryMode.
const (
	BESTEFFORT    TaskDeliveryMode = "BEST_EFFORT"
	FIREANDFORGET TaskDeliveryMode = "FIRE_AND_FORGET"
	GUARANTEED    TaskDeliveryMode = "GUARANTEED"
)

// Valid indicates whether the value is a known member of the TaskDeliveryMode enum.
func (e TaskDeliveryMode) Valid() bool {
	switch e {
	case BESTEFFORT:
		return true
	case FIREANDFORGET:
		return true
	case GUARANTEED:
		return true
	default:
		return false
	}
}

// Defines values for TaskPriorityClass.
const (
	BACKGROUND      TaskPriorityClass = "BACKGROUND"
	EMERGENCY       TaskPriorityClass = "EMERGENCY"
	HIGH            TaskPriorityClass = "HIGH"
	MISSIONCRITICAL TaskPriorityClass = "MISSION_CRITICAL"
	NORMAL          TaskPriorityClass = "NORMAL"
)

// Valid indicates whether the value is a known member of the TaskPriorityClass enum.
func (e TaskPriorityClass) Valid() bool {
	switch e {
	case BACKGROUND:
		return true
	case EMERGENCY:
		return true
	case HIGH:
		return true
	case MISSIONCRITICAL:
		return true
	case NORMAL:
		return true
	default:
		return false
	}
}

// Defines values for TaskRequirementsLatencyConstraintType.
const (
	TaskRequirementsLatencyConstraintTypeHARD      TaskRequirementsLatencyConstraintType = "HARD"
	TaskRequirementsLatencyConstraintTypeOBJECTIVE TaskRequirementsLatencyConstraintType = "OBJECTIVE"
	TaskRequirementsLatencyConstraintTypeSOFT      TaskRequirementsLatencyConstraintType = "SOFT"
)

// Valid indicates whether the value is a known member of the TaskRequirementsLatencyConstraintType enum.
func (e TaskRequirementsLatencyConstraintType) Valid() bool {
	switch e {
	case TaskRequirementsLatencyConstraintTypeHARD:
		return true
	case TaskRequirementsLatencyConstraintTypeOBJECTIVE:
		return true
	case TaskRequirementsLatencyConstraintTypeSOFT:
		return true
	default:
		return false
	}
}

// Defines values for TaskRequirementsReliabilityConstraintType.
const (
	HARD      TaskRequirementsReliabilityConstraintType = "HARD"
	OBJECTIVE TaskRequirementsReliabilityConstraintType = "OBJECTIVE"
	SOFT      TaskRequirementsReliabilityConstraintType = "SOFT"
)

// Valid indicates whether the value is a known member of the TaskRequirementsReliabilityConstraintType enum.
func (e TaskRequirementsReliabilityConstraintType) Valid() bool {
	switch e {
	case HARD:
		return true
	case OBJECTIVE:
		return true
	case SOFT:
		return true
	default:
		return false
	}
}

// Defines values for TaskStateStatus.
const (
	TaskStateStatusCANCELLED TaskStateStatus = "CANCELLED"
	TaskStateStatusCOMPLETED TaskStateStatus = "COMPLETED"
	TaskStateStatusFAILED    TaskStateStatus = "FAILED"
	TaskStateStatusPAUSED    TaskStateStatus = "PAUSED"
	TaskStateStatusPENDING   TaskStateStatus = "PENDING"
	TaskStateStatusRUNNING   TaskStateStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the TaskStateStatus enum.
func (e TaskStateStatus) Valid() bool {
	switch e {
	case TaskStateStatusCANCELLED:
		return true
	case TaskStateStatusCOMPLETED:
		return true
	case TaskStateStatusFAILED:
		return true
	case TaskStateStatusPAUSED:
		return true
	case TaskStateStatusPENDING:
		return true
	case TaskStateStatusRUNNING:
		return true
	default:
		return false
	}
}

// Defines values for WorldEventEventType.
const (
	WorldEventEventTypeENVIRONMENTCHANGE WorldEventEventType = "ENVIRONMENT_CHANGE"
	WorldEventEventTypeGENERIC           WorldEventEventType = "GENERIC"
	WorldEventEventTypeINTERFERENCE      WorldEventEventType = "INTERFERENCE"
	WorldEventEventTypeLINKFAILURE       WorldEventEventType = "LINK_FAILURE"
	WorldEventEventTypeNODEFAILURE       WorldEventEventType = "NODE_FAILURE"
	WorldEventEventTypeTERMINALFAILURE   WorldEventEventType = "TERMINAL_FAILURE"
)

// Valid indicates whether the value is a known member of the WorldEventEventType enum.
func (e WorldEventEventType) Valid() bool {
	switch e {
	case WorldEventEventTypeENVIRONMENTCHANGE:
		return true
	case WorldEventEventTypeGENERIC:
		return true
	case WorldEventEventTypeINTERFERENCE:
		return true
	case WorldEventEventTypeLINKFAILURE:
		return true
	case WorldEventEventTypeNODEFAILURE:
		return true
	case WorldEventEventTypeTERMINALFAILURE:
		return true
	default:
		return false
	}
}

// CommunicationTerminalCapability 节点通信终端的能力描述。Laser、RF、Microwave、Ethernet、Optical 等统一使用该抽象。终端能力描述“能做什么”，当前工作状态放在 CommunicationTerminalState。
type CommunicationTerminalCapability struct {
	// AntennaGain 天线增益。
	AntennaGain *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"antenna_gain,omitempty"`

	// AntennaType 天线/光学口径等终端辐射/接收结构类型。
	AntennaType *string `json:"antenna_type,omitempty"`

	// Duplex 双工模式。
	Duplex *CommunicationTerminalCapabilityDuplex `json:"duplex,omitempty"`

	// Enabled 该能力对象是否在本场景中启用。
	Enabled bool `json:"enabled"`

	// Extensions 终端类型特有的扩展能力参数。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// FieldOfView 终端视场角。
	FieldOfView *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"field_of_view,omitempty"`

	// MaxDataRate 终端理论最大数据速率。
	MaxDataRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"max_data_rate"`

	// MaxRange 终端理论最大通信距离。
	MaxRange *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"max_range,omitempty"`

	// MaxTrackingRate 最大跟踪角速度。
	MaxTrackingRate *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"max_tracking_rate,omitempty"`

	// MaxTransmitPower 最大发射功率。
	MaxTransmitPower *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"max_transmit_power,omitempty"`

	// PointingRequired 是否要求定向指向或跟踪，例如激光终端通常为 true。
	PointingRequired *bool `json:"pointing_required,omitempty"`

	// SupportedBands 支持的频段名称或项目内部频段标识。
	SupportedBands *[]string `json:"supported_bands,omitempty"`

	// SupportedFrequencies 支持的中心频率或离散频点列表；需要频段时可结合 supported_bands。
	SupportedFrequencies *[]float32 `json:"supported_frequencies,omitempty"`

	// TerminalId 通信终端在所属节点内的唯一标识。
	TerminalId string `json:"terminal_id"`

	// TerminalType 通信终端类型。
	TerminalType CommunicationTerminalCapabilityTerminalType `json:"terminal_type"`
}

// CommunicationTerminalCapabilityDuplex 双工模式。
type CommunicationTerminalCapabilityDuplex string

// CommunicationTerminalCapabilityTerminalType 通信终端类型。
type CommunicationTerminalCapabilityTerminalType string

// CommunicationTerminalState 通信终端在当前 scenario_time 下的动态运行状态。
type CommunicationTerminalState struct {
	// Active 终端当前是否处于激活/工作状态。
	Active bool `json:"active"`

	// CurrentFrequency 当前工作频率。
	CurrentFrequency *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"current_frequency,omitempty"`

	// CurrentPower 当前发射功率。
	CurrentPower *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"current_power,omitempty"`

	// Operational 终端是否处于可工作状态。
	Operational bool `json:"operational"`

	// PointingDirection 当前指向信息；具体坐标表达由数据源决定。
	PointingDirection *map[string]interface{} `json:"pointing_direction,omitempty"`

	// RxRate 当前接收速率。
	RxRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"rx_rate"`

	// TerminalId 引用所属节点 capabilities.communication_terminals 中的 terminal_id。
	TerminalId string `json:"terminal_id"`

	// TxRate 当前发送速率。
	TxRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"tx_rate"`
}

// ComputeCapability 节点的静态或慢变化计算能力。
type ComputeCapability struct {
	// CpuArchitecture CPU 架构，例如 x86_64、aarch64。
	CpuArchitecture *string `json:"cpu_architecture,omitempty"`

	// CpuComputeCapacity CPU 理论计算能力。
	CpuComputeCapacity *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"cpu_compute_capacity,omitempty"`

	// CpuCores CPU 逻辑/物理核心数，具体口径由数据源约定。
	CpuCores *int `json:"cpu_cores,omitempty"`

	// GpuComputeCapacity GPU 理论计算能力。
	GpuComputeCapacity *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"gpu_compute_capacity,omitempty"`

	// GpuCount GPU 数量。
	GpuCount *int `json:"gpu_count,omitempty"`

	// GpuModel GPU 型号。
	GpuModel *string `json:"gpu_model,omitempty"`

	// MemoryCapacity 内存总容量。
	MemoryCapacity *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"memory_capacity,omitempty"`
}

// Constraint defines model for Constraint.
type Constraint struct {
	// ConstraintType HARD=必须满足，SOFT=尽量满足，OBJECTIVE=优化方向。
	ConstraintType       ConstraintConstraintType `json:"constraint_type"`
	Enabled              bool                     `json:"enabled"`
	AdditionalProperties map[string]interface{}   `json:"-"`
}

// ConstraintConstraintType HARD=必须满足，SOFT=尽量满足，OBJECTIVE=优化方向。
type ConstraintConstraintType string

// ConsumerRef defines model for ConsumerRef.
type ConsumerRef struct {
	ConsumerId string `json:"consumer_id"`

	// Type 资源消费者类型。
	Type ConsumerRefType `json:"type"`
}

// ConsumerRefType 资源消费者类型。
type ConsumerRefType string

// DerivedMetrics 所有可由底层状态派生的聚合指标。
type DerivedMetrics struct {
	// Network 由基础状态计算得到、用于训练辅助任务、评估和可视化的网络级指标。
	Network NetworkDerivedMetrics `json:"network"`
	Tasks   TaskDerivedMetrics    `json:"tasks"`
}

// Destination L3 Reachability / Forwarding 的目的对象。
type Destination struct {
	// Type 目的对象类型。
	Type DestinationType `json:"type"`

	// Value node_id、IP prefix 或具体 IP address。
	Value string `json:"value"`
}

// DestinationType 目的对象类型。
type DestinationType string

// ExternalAction 从 Network World Model 系统边界之外主动施加的干预。一次 Action 发生后，其影响应反映在后续 World State 中。
type ExternalAction struct {
	ActionId string `json:"action_id"`

	// ActionType 外部主动干预类型。
	ActionType ExternalActionActionType `json:"action_type"`

	// ExecutedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ExecutedAt ScenarioTime `json:"executed_at"`

	// Parameters Action 特有参数。例如 TASK_SUBMIT 可包含 task 定义，INTENT_CHANGE 可包含新的 intent 字段。
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Target     TargetRef               `json:"target"`
}

// ExternalActionActionType 外部主动干预类型。
type ExternalActionActionType string

// Flow 由 Traffic Demand 实际形成的网络传输流。
type Flow struct {
	DemandId        *string `json:"demand_id,omitempty"`
	DestinationNode string  `json:"destination_node"`
	FlowId          string  `json:"flow_id"`

	// PathId 可选引用当前派生 Path。
	PathId     *string `json:"path_id,omitempty"`
	SourceNode string  `json:"source_node"`

	// State 实际网络流在当前 scenario_time 下的状态。
	State  FlowState `json:"state"`
	TaskId *string   `json:"task_id,omitempty"`

	// TransportType 传输类型；仅作为 Flow 特征，不绑定模型结构。
	TransportType FlowTransportType `json:"transport_type"`
}

// FlowTransportType 传输类型；仅作为 Flow 特征，不绑定模型结构。
type FlowTransportType string

// FlowState 实际网络流在当前 scenario_time 下的状态。
type FlowState struct {
	// ActualThroughput 实际有效吞吐。
	ActualThroughput struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"actual_throughput"`

	// AllocatedRate 网络为该 Flow 分配的速率/带宽。
	AllocatedRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"allocated_rate"`

	// BytesDelivered 目的端已经成功接收的字节数。
	BytesDelivered struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_delivered"`

	// BytesRemaining 剩余待发送/待完成字节数。
	BytesRemaining *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"bytes_remaining,omitempty"`

	// BytesSent 源端已经发送的字节数。
	BytesSent struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_sent"`

	// BytesTotal Flow 总字节数。
	BytesTotal *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"bytes_total,omitempty"`
	LossRate float32 `json:"loss_rate"`

	// OfferedRate 数据源实际尝试发送的速率。
	OfferedRate struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"offered_rate"`

	// Rtt 往返时延。
	Rtt *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"rtt,omitempty"`

	// Status Flow 生命周期状态。
	Status FlowStateStatus `json:"status"`
}

// FlowStateStatus Flow 生命周期状态。
type FlowStateStatus string

// ForwardingEntry 协议无关的 L3 转发结果。记录当前实际上如何转发，不记录 OSPF/BGP/IS-IS 等机制如何得到该结果。
type ForwardingEntry struct {
	// Destination L3 Reachability / Forwarding 的目的对象。
	Destination Destination `json:"destination"`

	// ForwardingId Forwarding Entry 唯一 ID。
	ForwardingId   string `json:"forwarding_id"`
	NetworkContext string `json:"network_context"`

	// NextHops 有效下一跳集合。
	NextHops []NextHop `json:"next_hops"`

	// NodeId 执行该转发决策的节点。
	NodeId string `json:"node_id"`

	// ValidFrom 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ValidFrom ScenarioTime `json:"valid_from"`

	// ValidUntil 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ValidUntil *ScenarioTime `json:"valid_until,omitempty"`
}

// IPAddress L3 地址信息。
type IPAddress struct {
	// Address IPv4 或 IPv6 地址字符串。
	Address string `json:"address"`

	// Family 地址族。
	Family IPAddressFamily `json:"family"`

	// PrefixLength 前缀长度。
	PrefixLength int `json:"prefix_length"`

	// Primary 是否为该 L3 接口主地址。
	Primary bool `json:"primary"`
}

// IPAddressFamily 地址族。
type IPAddressFamily string

// L2Endpoint L2 Link 的端点。必须同时指向 Node 和该 Node 上的通信终端。
type L2Endpoint struct {
	// NodeId 引用 nodes[].node_id。
	NodeId string `json:"node_id"`

	// TerminalId 引用对应节点的 communication terminal。
	TerminalId string `json:"terminal_id"`
}

// L2Link 两个通信终端之间当前存在的二层/通信层连接状态。星间、星地、地面、空地等统一建模。
type L2Link struct {
	// AvailableBandwidth 当前可用带宽。
	AvailableBandwidth struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"available_bandwidth"`

	// BitErrorRate 可选比特误码率，0~1。
	BitErrorRate *float32 `json:"bit_error_rate,omitempty"`

	// Capacity 当前有效容量。
	Capacity struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"capacity"`

	// Enabled 该 Link 是否属于当前场景配置。
	Enabled bool `json:"enabled"`

	// EndpointA L2 Link 的端点。必须同时指向 Node 和该 Node 上的通信终端。
	EndpointA L2Endpoint `json:"endpoint_a"`

	// EndpointB L2 Link 的端点。必须同时指向 Node 和该 Node 上的通信终端。
	EndpointB L2Endpoint `json:"endpoint_b"`

	// Extensions 链路扩展字段。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// Jitter 时延抖动。
	Jitter struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"jitter"`

	// LinkClass 场景语义上的链路分类。
	LinkClass L2LinkLinkClass `json:"link_class"`

	// LinkId L2 Link 全局唯一标识。
	LinkId string `json:"link_id"`

	// MaxCapacity 链路静态/理论最大容量。
	MaxCapacity struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"max_capacity"`

	// Medium 实际通信媒介。
	Medium L2LinkMedium `json:"medium"`

	// Operational 链路当前是否可工作。
	Operational bool `json:"operational"`

	// PacketLossRate 包丢失率，0~1。
	PacketLossRate float32 `json:"packet_loss_rate"`

	// PropagationDelay 传播时延。
	PropagationDelay struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"propagation_delay"`

	// Queue 链路或接口上的队列状态。第一阶段可只采集可获得的聚合队列指标。
	Queue *QueueState `json:"queue,omitempty"`

	// Status 链路当前运行状态。
	Status L2LinkStatus `json:"status"`

	// TransmissionDelay 发送/序列化时延。
	TransmissionDelay *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"transmission_delay,omitempty"`

	// Utilization 当前利用率。通常建议 0~1；允许数据源保留>1以表达过载时需在导入规范中明确。
	Utilization float32 `json:"utilization"`
}

// L2LinkLinkClass 场景语义上的链路分类。
type L2LinkLinkClass string

// L2LinkMedium 实际通信媒介。
type L2LinkMedium string

// L2LinkStatus 链路当前运行状态。
type L2LinkStatus string

// L2Network 当前 scenario_time 下的通信/L2 网络。
type L2Network struct {
	Links []L2Link `json:"links"`
}

// L3AggregateState 由 L3 状态派生得到的宏观网络指标。
type L3AggregateState struct {
	// ConnectedComponents 当前三层连通分量数量。
	ConnectedComponents *int `json:"connected_components,omitempty"`

	// IsolatedNodes 当前孤立节点 ID。
	IsolatedNodes *[]string `json:"isolated_nodes,omitempty"`

	// ReachablePairRatio 可达节点对比例。
	ReachablePairRatio *float32 `json:"reachable_pair_ratio,omitempty"`
}

// L3Interface 节点上的三层逻辑接口。可关联底层通信终端。
type L3Interface struct {
	Addresses []IPAddress `json:"addresses"`

	// Enabled 接口是否启用。
	Enabled bool `json:"enabled"`

	// L3InterfaceId L3 接口全局唯一 ID。
	L3InterfaceId string `json:"l3_interface_id"`

	// Mtu 接口 MTU。
	Mtu struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"mtu"`

	// NetworkContext 逻辑网络上下文，例如 default、VRF/租户/Overlay 标识。
	NetworkContext string `json:"network_context"`

	// NodeId 所属节点 ID。
	NodeId string `json:"node_id"`

	// TerminalId 可选关联的 L2/通信终端 ID。
	TerminalId *string `json:"terminal_id,omitempty"`
}

// L3LogicalEndpoint defines model for L3LogicalEndpoint.
type L3LogicalEndpoint struct {
	L3InterfaceId string `json:"l3_interface_id"`
	NodeId        string `json:"node_id"`
}

// L3LogicalLink 协议无关的三层逻辑直接连接。它不是 OSPF/BGP 邻居关系，可代表 DIRECT、TUNNEL、OVERLAY 等逻辑连接。
type L3LogicalLink struct {
	EndpointA L3LogicalEndpoint `json:"endpoint_a"`
	EndpointB L3LogicalEndpoint `json:"endpoint_b"`

	// LogicalLinkId 三层逻辑链路唯一 ID。
	LogicalLinkId  string `json:"logical_link_id"`
	NetworkContext string `json:"network_context"`

	// Operational 逻辑链路当前是否有效。
	Operational bool `json:"operational"`

	// Type 三层逻辑连接类型。
	Type L3LogicalLinkType `json:"type"`
}

// L3LogicalLinkType 三层逻辑连接类型。
type L3LogicalLinkType string

// L3Network 协议无关的 L3 Network State。
type L3Network struct {
	// AggregateState 由 L3 状态派生得到的宏观网络指标。
	AggregateState    *L3AggregateState       `json:"aggregate_state,omitempty"`
	Extensions        *map[string]interface{} `json:"extensions,omitempty"`
	ForwardingEntries []ForwardingEntry       `json:"forwarding_entries"`
	Interfaces        []L3Interface           `json:"interfaces"`
	LogicalLinks      []L3LogicalLink         `json:"logical_links"`
	Paths             *[]L3Path               `json:"paths,omitempty"`
	Reachability      *[]ReachabilityEntry    `json:"reachability,omitempty"`
}

// L3Path 根据 Forwarding State 派生得到的端到端路径。
type L3Path struct {
	Derived         L3PathDerived `json:"derived"`
	DestinationNode string        `json:"destination_node"`
	LogicalLinks    []string      `json:"logical_links"`

	// Metrics 由 Path 与底层 Link/Traffic 状态推导出的端到端路径指标。
	Metrics        PathMetrics `json:"metrics"`
	NetworkContext string      `json:"network_context"`
	Nodes          []string    `json:"nodes"`
	PathId         string      `json:"path_id"`
	SourceNode     string      `json:"source_node"`
	Valid          bool        `json:"valid"`
}

// L3PathDerived defines model for L3Path.Derived.
type L3PathDerived bool

// NetworkDerivedMetrics 由基础状态计算得到、用于训练辅助任务、评估和可视化的网络级指标。
type NetworkDerivedMetrics struct {
	AveragePathLength *float32 `json:"average_path_length,omitempty"`

	// AverageRtt 全网平均 RTT。
	AverageRtt *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"average_rtt,omitempty"`
	CongestedLinkCount     *int     `json:"congested_link_count,omitempty"`
	MaximumLinkUtilization *float32 `json:"maximum_link_utilization,omitempty"`
	PacketLossRate         *float32 `json:"packet_loss_rate,omitempty"`
	ReachablePairRatio     *float32 `json:"reachable_pair_ratio,omitempty"`
}

// NetworkIntent 网络系统当前的高层目标和任务保障倾向。它不描述具体控制协议，而作为内部 Network Dynamics 的条件。
type NetworkIntent struct {
	Connectivity struct {
		Enabled bool `json:"enabled"`

		// MinimumReachablePairRatio 可选最低全局可达节点对比例。
		MinimumReachablePairRatio  *float32 `json:"minimum_reachable_pair_ratio,omitempty"`
		PreserveGlobalConnectivity bool     `json:"preserve_global_connectivity"`
	} `json:"connectivity"`
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// ObjectiveWeights 可选高层目标权重，可用于条件化世界模型或后续控制研究。
	ObjectiveWeights *struct {
		Connectivity       *float32 `json:"connectivity,omitempty"`
		Latency            *float32 `json:"latency,omitempty"`
		Reliability        *float32 `json:"reliability,omitempty"`
		ResourceEfficiency *float32 `json:"resource_efficiency,omitempty"`
		TaskAssurance      *float32 `json:"task_assurance,omitempty"`
	} `json:"objective_weights,omitempty"`
	ResourceEfficiency struct {
		AvoidCongestion bool `json:"avoid_congestion"`
		Enabled         bool `json:"enabled"`
		LoadBalance     bool `json:"load_balance"`
	} `json:"resource_efficiency"`
	TaskAssurance struct {
		Enabled           bool `json:"enabled"`
		PreemptionAllowed bool `json:"preemption_allowed"`
		PriorityAware     bool `json:"priority_aware"`
		RespectTaskQos    bool `json:"respect_task_qos"`
	} `json:"task_assurance"`
}

// NetworkWorldState Network World State v0.1 的顶层快照对象。它表示某一个唯一 scenario_time 下，物理环境、节点、L2、L3、流量/资源、任务和网络意图的完整状态。
type NetworkWorldState struct {
	// DeltaTime 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	DeltaTime *ScenarioTime `json:"delta_time,omitempty"`

	// DerivedMetrics 所有可由底层状态派生的聚合指标。
	DerivedMetrics *DerivedMetrics `json:"derived_metrics,omitempty"`

	// Events 与当前快照相关、在该时间窗口内发生的 Event。
	Events []WorldEvent `json:"events"`

	// Extensions 顶层扩展字段。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// ExternalActions 与当前快照相关、在该时间窗口内发生的外部主动 Action。
	ExternalActions []ExternalAction `json:"external_actions"`

	// L2Network 当前 scenario_time 下的通信/L2 网络。
	L2Network L2Network `json:"l2_network"`

	// L3Network 协议无关的 L3 Network State。
	L3Network L3Network `json:"l3_network"`

	// NetworkIntent 网络系统当前的高层目标和任务保障倾向。它不描述具体控制协议，而作为内部 Network Dynamics 的条件。
	NetworkIntent NetworkIntent `json:"network_intent"`
	Nodes         []Node        `json:"nodes"`

	// PhysicalWorld 节点之外客观存在的物理环境。用于描述空间、地理、大气、电磁、干扰及传播环境。节点的位置、速度、姿态等属于 Node State。
	PhysicalWorld PhysicalWorld `json:"physical_world"`

	// ScenarioTime 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	ScenarioTime ScenarioTime `json:"scenario_time"`

	// Schema 标识当前 Network World State 数据契约的名称和版本。
	Schema SchemaMetadata `json:"schema"`

	// SnapshotId 当前 World Snapshot 唯一标识。
	SnapshotId      string          `json:"snapshot_id"`
	Tasks           []Task          `json:"tasks"`
	TrafficResource TrafficResource `json:"traffic_resource"`

	// WorldId 场景/世界唯一标识。
	WorldId string `json:"world_id"`
}

// NextHop 当前节点针对指定目的的实际下一跳。用于表达单路径、ECMP 或加权多路径。
type NextHop struct {
	// L3InterfaceId 出接口。
	L3InterfaceId string `json:"l3_interface_id"`

	// NodeId 下一跳节点。
	NodeId string `json:"node_id"`

	// Weight 多路径权重。单路径通常为 1。
	Weight float32 `json:"weight"`
}

// Node 网络世界中的独立物理设备或平台。卫星、地面站、飞机、无人机、车辆、舰船、服务器等统一建模为 Node。
type Node struct {
	// Capabilities 节点作为独立硬件个体所具备的静态/慢变化能力集合。
	Capabilities NodeCapabilities `json:"capabilities"`

	// Enabled 节点是否属于当前场景。
	Enabled bool `json:"enabled"`

	// Extensions 节点级扩展字段。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// Name 可读名称。
	Name *string `json:"name,omitempty"`

	// NodeId 在 world_id 范围内全局唯一的节点 ID。
	NodeId string `json:"node_id"`

	// NodeType 节点类型。该枚举用于分类，不应驱动核心模型中的场景特化逻辑。
	NodeType NodeNodeType `json:"node_type"`

	// State 节点在当前 scenario_time 下的动态状态。
	State NodeState `json:"state"`
}

// NodeNodeType 节点类型。该枚举用于分类，不应驱动核心模型中的场景特化逻辑。
type NodeNodeType string

// NodeCapabilities 节点作为独立硬件个体所具备的静态/慢变化能力集合。
type NodeCapabilities struct {
	CommunicationTerminals []CommunicationTerminalCapability `json:"communication_terminals"`

	// Compute 节点的静态或慢变化计算能力。
	Compute *ComputeCapability `json:"compute,omitempty"`

	// Extensions 节点特有能力扩展。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`
	Payloads   *[]PayloadCapability    `json:"payloads,omitempty"`

	// StorageCapacity 节点本地存储总容量。
	StorageCapacity *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"storage_capacity,omitempty"`
}

// NodeState 节点在当前 scenario_time 下的动态状态。
type NodeState struct {
	CommunicationTerminals []CommunicationTerminalState `json:"communication_terminals"`

	// CpuUtilization CPU 利用率，统一使用 0~1。
	CpuUtilization *float32 `json:"cpu_utilization,omitempty"`

	// Extensions 节点动态状态扩展。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// Faults 当前生效的故障/异常标识。
	Faults *[]string `json:"faults,omitempty"`

	// GpuUtilization GPU 利用率，统一使用 0~1。
	GpuUtilization *float32 `json:"gpu_utilization,omitempty"`

	// HealthScore 可选健康度，0 表示完全不可用，1 表示完全健康。
	HealthScore *float32 `json:"health_score,omitempty"`

	// MemoryUtilization 内存利用率，统一使用 0~1。
	MemoryUtilization *float32 `json:"memory_utilization,omitempty"`

	// Operational 节点整体是否处于工作状态。
	Operational bool `json:"operational"`

	// Orientation 节点姿态。对需要指向、波束、平台姿态等场景有意义。
	Orientation *Orientation `json:"orientation,omitempty"`

	// Position 节点在当前 scenario_time 下的位置状态。位置属于 Node State，而不是 Physical World。
	Position Position `json:"position"`

	// Velocity 节点在当前 scenario_time 下相对于 position.frame 的速度。
	Velocity Velocity `json:"velocity"`
}

// Orientation 节点姿态。对需要指向、波束、平台姿态等场景有意义。
type Orientation struct {
	// Pitch 俯仰角。
	Pitch *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"pitch,omitempty"`

	// Roll 横滚角。
	Roll *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"roll,omitempty"`

	// Yaw 偏航角。
	Yaw *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"yaw,omitempty"`
}

// PathMetrics 由 Path 与底层 Link/Traffic 状态推导出的端到端路径指标。
type PathMetrics struct {
	// BottleneckCapacity 路径瓶颈容量。
	BottleneckCapacity struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bottleneck_capacity"`
	HopCount       int     `json:"hop_count"`
	PacketLossRate float32 `json:"packet_loss_rate"`

	// TotalDelay 端到端总时延。
	TotalDelay struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"total_delay"`
}

// PayloadCapability 节点搭载的任务载荷或功能载荷，例如雷达、相机、传感器或专用处理载荷。
type PayloadCapability struct {
	// Capabilities 载荷特有能力参数。
	Capabilities *map[string]interface{} `json:"capabilities,omitempty"`

	// PayloadId 载荷在节点内的唯一标识。
	PayloadId string `json:"payload_id"`

	// PayloadType 载荷类型。该字段保持开放，便于适配不同仿真系统。
	PayloadType string `json:"payload_type"`
}

// PhysicalWorld 节点之外客观存在的物理环境。用于描述空间、地理、大气、电磁、干扰及传播环境。节点的位置、速度、姿态等属于 Node State。
type PhysicalWorld struct {
	// Atmosphere 大气环境条件。可由仿真系统直接采集并映射。
	Atmosphere *struct {
		// CloudAttenuation 云衰减。
		CloudAttenuation *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"cloud_attenuation,omitempty"`

		// Humidity 相对湿度，建议使用 0~1。
		Humidity *float32 `json:"humidity,omitempty"`

		// Pressure 环境气压。
		Pressure *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"pressure,omitempty"`

		// RainRate 降雨率。
		RainRate *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"rain_rate,omitempty"`

		// Temperature 环境温度。
		Temperature *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"temperature,omitempty"`
	} `json:"atmosphere,omitempty"`

	// ElectromagneticEnvironment 电磁背景、噪声和干扰环境。
	ElectromagneticEnvironment *struct {
		// BackgroundNoise 背景噪声功率。
		BackgroundNoise *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"background_noise,omitempty"`

		// InterferenceRegions 场景中的干扰区域或干扰源集合。
		InterferenceRegions *[]struct {
			// Description 干扰源的人类可读说明。
			Description *string `json:"description,omitempty"`

			// InterferenceId 干扰对象唯一标识。
			InterferenceId string `json:"interference_id"`

			// Parameters 由数据源提供的干扰参数。Schema 对其保持开放。
			Parameters *map[string]interface{} `json:"parameters,omitempty"`
		} `json:"interference_regions,omitempty"`
	} `json:"electromagnetic_environment,omitempty"`

	// EnvironmentType 场景的宏观物理环境分类，仅用于描述和筛选，不决定核心计算逻辑。
	EnvironmentType PhysicalWorldEnvironmentType `json:"environment_type"`

	// Extensions 物理世界的扩展属性。扩展字段不应改变核心 Schema 语义。
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// SpatialEnvironment 空间/地理参考环境。
	SpatialEnvironment struct {
		// DefaultReferenceFrame 场景默认坐标参考系；节点可覆盖并显式声明自己的 frame。
		DefaultReferenceFrame string `json:"default_reference_frame"`

		// EarthModel 地球模型或参考椭球，例如 WGS84。
		EarthModel *string `json:"earth_model,omitempty"`

		// ObstacleModelId 外部障碍物模型标识。
		ObstacleModelId *string `json:"obstacle_model_id,omitempty"`

		// TerrainModelId 外部地形模型标识。
		TerrainModelId *string `json:"terrain_model_id,omitempty"`
	} `json:"spatial_environment"`
}

// PhysicalWorldEnvironmentType 场景的宏观物理环境分类，仅用于描述和筛选，不决定核心计算逻辑。
type PhysicalWorldEnvironmentType string

// Position 节点在当前 scenario_time 下的位置状态。位置属于 Node State，而不是 Physical World。
type Position struct {
	// Frame 坐标参考系，例如 ECEF、ECI、WGS84 或项目自定义参考系。
	Frame string `json:"frame"`

	// X X 轴坐标。
	X struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"x"`

	// Y Y 轴坐标。
	Y struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"y"`

	// Z Z 轴坐标。
	Z struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"z"`
}

// QueueState 链路或接口上的队列状态。第一阶段可只采集可获得的聚合队列指标。
type QueueState struct {
	// QueueCapacity 队列容量。
	QueueCapacity *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"queue_capacity,omitempty"`

	// QueueDepth 当前排队数据量。
	QueueDepth *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"queue_depth,omitempty"`

	// Utilization 队列利用率，0~1。
	Utilization *float32 `json:"utilization,omitempty"`
}

// ReachabilityEntry 从一个源节点到一个 L3 目的对象的可达性。通常可以作为 Derived State。
type ReachabilityEntry struct {
	// Derived 标识该记录为派生状态。
	Derived ReachabilityEntryDerived `json:"derived"`

	// Destination L3 Reachability / Forwarding 的目的对象。
	Destination Destination `json:"destination"`
	Reachable   bool        `json:"reachable"`
	SourceNode  string      `json:"source_node"`
}

// ReachabilityEntryDerived 标识该记录为派生状态。
type ReachabilityEntryDerived bool

// ResourceAllocation 显式表示网络资源当前被谁占用多少，用于学习任务保障、抢占和资源倾斜规律。
type ResourceAllocation struct {
	AllocationId string `json:"allocation_id"`

	// Bandwidth 为消费者分配的带宽。
	Bandwidth *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"bandwidth,omitempty"`

	// Compute 为消费者分配的计算资源。
	Compute *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"compute,omitempty"`
	Consumer ConsumerRef `json:"consumer"`

	// Priority 该资源分配记录对应的调度优先级。
	Priority *int        `json:"priority,omitempty"`
	Resource ResourceRef `json:"resource"`
}

// ResourceRef defines model for ResourceRef.
type ResourceRef struct {
	// ResourceId 对应资源对象 ID。
	ResourceId string `json:"resource_id"`

	// Type 被分配的资源类型。
	Type ResourceRefType `json:"type"`
}

// ResourceRefType 被分配的资源类型。
type ResourceRefType string

// ScenarioTime 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
type ScenarioTime struct {
	// Unit 场景时间统一以秒表示。
	Unit ScenarioTimeUnit `json:"unit"`

	// Value 自场景起点开始累计的时间值。
	Value float32 `json:"value"`
}

// ScenarioTimeUnit 场景时间统一以秒表示。
type ScenarioTimeUnit string

// SchemaMetadata 标识当前 Network World State 数据契约的名称和版本。
type SchemaMetadata struct {
	// Name Schema 固定名称。
	Name SchemaMetadataName `json:"name"`

	// Version Schema 版本。第一阶段建议使用语义化或显式版本号，例如 0.1。
	Version string `json:"version"`
}

// SchemaMetadataName Schema 固定名称。
type SchemaMetadataName string

// TargetRef defines model for TargetRef.
type TargetRef struct {
	// Id 目标对象 ID。全局对象可为空，例如 PHYSICAL_WORLD。
	Id *string `json:"id,omitempty"`

	// Type 事件或外部行为的目标对象类型。
	Type TargetRefType `json:"type"`
}

// TargetRefType 事件或外部行为的目标对象类型。
type TargetRefType string

// Task 第一阶段统一业务/任务抽象。Task 可产生 0..N Traffic Demand，并通过 requirements 表达任务保障目标。
type Task struct {
	// CanPreemptOthers 该任务是否允许抢占其他任务资源。
	CanPreemptOthers bool `json:"can_preempt_others"`

	// CompletionCriterion 任务完成的判定语义。
	CompletionCriterion TaskCompletionCriterion `json:"completion_criterion"`

	// Deadline 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	Deadline *ScenarioTime `json:"deadline,omitempty"`

	// DeliveryMode GUARANTEED=强调成功交付，BEST_EFFORT=尽力而为，FIRE_AND_FORGET=源端发出即可。
	DeliveryMode TaskDeliveryMode `json:"delivery_mode"`
	Destinations []string         `json:"destinations"`

	// EarliestStart 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	EarliestStart *ScenarioTime           `json:"earliest_start,omitempty"`
	Extensions    *map[string]interface{} `json:"extensions,omitempty"`

	// PayloadSize 任务总负载/数据规模。
	PayloadSize struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"payload_size"`

	// Preemptible 该任务自身是否允许被其他任务抢占。
	Preemptible bool `json:"preemptible"`

	// Priority 任务优先级。数值用于精细比较，class 用于语义分类。
	Priority TaskPriority `json:"priority"`

	// Requirements 任务对网络和执行过程提出的约束与优化目标。
	Requirements TaskRequirements `json:"requirements"`
	SourceNode   string           `json:"source_node"`

	// State 任务在当前 scenario_time 下的执行状态。
	State TaskState `json:"state"`

	// SubmittedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	SubmittedAt ScenarioTime `json:"submitted_at"`
	TaskId      string       `json:"task_id"`

	// TaskType 任务类型，由业务系统定义。
	TaskType string `json:"task_type"`
}

// TaskCompletionCriterion 任务完成的判定语义。
type TaskCompletionCriterion string

// TaskDeliveryMode GUARANTEED=强调成功交付，BEST_EFFORT=尽力而为，FIRE_AND_FORGET=源端发出即可。
type TaskDeliveryMode string

// TaskDerivedMetrics defines model for TaskDerivedMetrics.
type TaskDerivedMetrics struct {
	CompletedTasks                *int     `json:"completed_tasks,omitempty"`
	DeadlineViolationCount        *int     `json:"deadline_violation_count,omitempty"`
	FailedTasks                   *int     `json:"failed_tasks,omitempty"`
	HighPrioritySatisfactionRatio *float32 `json:"high_priority_satisfaction_ratio,omitempty"`
	RunningTasks                  *int     `json:"running_tasks,omitempty"`
	TotalTasks                    *int     `json:"total_tasks,omitempty"`
}

// TaskPriority 任务优先级。数值用于精细比较，class 用于语义分类。
type TaskPriority struct {
	// Class 语义优先级。
	Class TaskPriorityClass `json:"class"`

	// Value 优先级数值，值越大表示优先级越高。
	Value int `json:"value"`
}

// TaskPriorityClass 语义优先级。
type TaskPriorityClass string

// TaskRequirements 任务对网络和执行过程提出的约束与优化目标。
type TaskRequirements struct {
	Completion struct {
		// DeadlineRequired 是否要求在 deadline 前完成。
		DeadlineRequired bool `json:"deadline_required"`

		// MustComplete 任务是否要求最终完成。
		MustComplete bool `json:"must_complete"`
	} `json:"completion"`
	Latency struct {
		// ConstraintType 时延要求约束类型。
		ConstraintType TaskRequirementsLatencyConstraintType `json:"constraint_type"`
		Enabled        bool                                  `json:"enabled"`

		// Max 任务允许的最大时延。
		Max *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"max,omitempty"`
	} `json:"latency"`
	Reliability struct {
		// ConstraintType 可靠性约束类型。
		ConstraintType TaskRequirementsReliabilityConstraintType `json:"constraint_type"`
		Enabled        bool                                      `json:"enabled"`

		// MinimumDeliveryProbability 最低成功交付概率。
		MinimumDeliveryProbability *float32 `json:"minimum_delivery_probability,omitempty"`
	} `json:"reliability"`
	Throughput struct {
		Enabled bool `json:"enabled"`

		// Minimum 最低吞吐要求。
		Minimum *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"minimum,omitempty"`

		// Preferred 偏好的目标吞吐。
		Preferred *struct {
			// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
			Unit string `json:"unit"`

			// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
			Value *float32 `json:"value"`
		} `json:"preferred,omitempty"`
	} `json:"throughput"`
}

// TaskRequirementsLatencyConstraintType 时延要求约束类型。
type TaskRequirementsLatencyConstraintType string

// TaskRequirementsReliabilityConstraintType 可靠性约束类型。
type TaskRequirementsReliabilityConstraintType string

// TaskState 任务在当前 scenario_time 下的执行状态。
type TaskState struct {
	// BytesDelivered 目的端已成功交付数据量。
	BytesDelivered struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_delivered"`

	// BytesSent 源端已发送数据量。
	BytesSent struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_sent"`

	// BytesTotal 任务总数据量。
	BytesTotal struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"bytes_total"`

	// CompletedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	CompletedAt *ScenarioTime `json:"completed_at,omitempty"`

	// EstimatedCompletionTime 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	EstimatedCompletionTime *ScenarioTime `json:"estimated_completion_time,omitempty"`

	// Progress 任务完成进度 0~1。
	Progress float32 `json:"progress"`

	// RequirementSatisfaction 当前任务关键要求是否被满足；unknown 可用 null 表示。
	RequirementSatisfaction *struct {
		DeadlineSatisfied    *bool `json:"deadline_satisfied,omitempty"`
		LatencySatisfied     *bool `json:"latency_satisfied,omitempty"`
		ReliabilitySatisfied *bool `json:"reliability_satisfied,omitempty"`
		ThroughputSatisfied  *bool `json:"throughput_satisfied,omitempty"`
	} `json:"requirement_satisfaction,omitempty"`

	// StartedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	StartedAt *ScenarioTime `json:"started_at,omitempty"`

	// Status 任务生命周期状态。
	Status TaskStateStatus `json:"status"`
}

// TaskStateStatus 任务生命周期状态。
type TaskStateStatus string

// TrafficAggregateState defines model for TrafficAggregateState.
type TrafficAggregateState struct {
	// CongestedLinks 被判定为拥塞的 link_id 列表。
	CongestedLinks []string `json:"congested_links"`

	// TotalDeliveredTraffic 全网总 delivered traffic。
	TotalDeliveredTraffic struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"total_delivered_traffic"`

	// TotalOfferedTraffic 全网总 offered traffic。
	TotalOfferedTraffic struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"total_offered_traffic"`
}

// TrafficDemand 尚未等价于实际 Flow 的网络通信需求：描述谁想向谁发送多少数据或多大速率。
type TrafficDemand struct {
	DemandId        string `json:"demand_id"`
	DestinationNode string `json:"destination_node"`

	// GeneratedAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	GeneratedAt ScenarioTime `json:"generated_at"`

	// RequestedRate 期望速率。
	RequestedRate *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"requested_rate,omitempty"`
	SourceNode string `json:"source_node"`

	// TaskId 产生该需求的 Task，可为空。
	TaskId *string `json:"task_id,omitempty"`

	// TotalDataSize 待传输数据总量。
	TotalDataSize *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"total_data_size,omitempty"`
}

// TrafficResource defines model for TrafficResource.
type TrafficResource struct {
	AggregateState *TrafficAggregateState `json:"aggregate_state,omitempty"`
	Allocations    []ResourceAllocation   `json:"allocations"`
	Demands        []TrafficDemand        `json:"demands"`
	Flows          []Flow                 `json:"flows"`
}

// Velocity 节点在当前 scenario_time 下相对于 position.frame 的速度。
type Velocity struct {
	// Vx X 轴速度。
	Vx struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"vx"`

	// Vy Y 轴速度。
	Vy struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"vy"`

	// Vz Z 轴速度。
	Vz struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value float32 `json:"value"`
	} `json:"vz"`
}

// WorldEvent 发生在世界中的外部事件，例如自然故障、干扰或环境变化。
type WorldEvent struct {
	// Duration 事件持续时间。
	Duration *struct {
		// Unit 物理单位。建议使用约定的标准缩写，例如 s、m、bps、byte、W、dB、dBm、Pa、K。
		Unit string `json:"unit"`

		// Value 数值。为空表示该指标当前未采集、不可用或不适用于当前对象。
		Value *float32 `json:"value"`
	} `json:"duration,omitempty"`
	EventId string `json:"event_id"`

	// EventType 事件类型。
	EventType WorldEventEventType `json:"event_type"`

	// OccurredAt 场景内部唯一时间轴。Network World State 中所有动态状态都必须与 scenario_time 对齐。该时间只表达场景时间，不区分现实时间、虚拟时间或仿真时间来源。
	OccurredAt ScenarioTime `json:"occurred_at"`

	// Parameters 事件特有参数，例如故障程度、干扰功率、环境变化量。
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Target     TargetRef               `json:"target"`
}

// WorldEventEventType 事件类型。
type WorldEventEventType string

// Getter for additional properties for Constraint. Returns the specified
// element and whether it was found
func (a Constraint) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Constraint
func (a *Constraint) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Constraint to handle AdditionalProperties
func (a *Constraint) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["constraint_type"]; found {
		err = json.Unmarshal(raw, &a.ConstraintType)
		if err != nil {
			return fmt.Errorf("error reading 'constraint_type': %w", err)
		}
		delete(object, "constraint_type")
	}

	if raw, found := object["enabled"]; found {
		err = json.Unmarshal(raw, &a.Enabled)
		if err != nil {
			return fmt.Errorf("error reading 'enabled': %w", err)
		}
		delete(object, "enabled")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Constraint to handle AdditionalProperties
func (a Constraint) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["constraint_type"], err = json.Marshal(a.ConstraintType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'constraint_type': %w", err)
	}

	object["enabled"], err = json.Marshal(a.Enabled)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'enabled': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
